#! /bin/sh
case $# in
    1) ;;
    *) echo "Usage: nexe2nmf <file.nexe>">&2;exit 1;;
esac
fn=`echo "$1" | sed -e 's/[.]nexe$//'`.nmf
cat > $fn << EOF
{
  "nexes": {
    "x86-32": "$1",
  }
}
EOF
exit 0
