'\"
'\" Copyright (c) 2018 Tcl Core Team
'\"
'\" See the file "license.terms" for information on usage and redistribution
'\" of this file, and for a DISCLAIMER OF ALL WARRANTIES.
'\"
.so man.macros
.TH Tcl_InitSubsystems 3 9.0 Tcl "Tcl Library Procedures"
.BS
.SH NAME
Tcl_InitSubsystems \- initialize the Tcl library.
.SH SYNOPSIS
.nf
\fB#include <tcl.h>\fR
.sp
const char *
\fBTcl_InitSubsystems\fR()
.fi
.BE

.SH DESCRIPTION
.PP
The \fBTcl_InitSubsystems\fR procedure initializes various Tcl subsystems. It
should be called by any additional Tcl threads created after the main thread in
a Tcl application that wish to use Tcl facilities without creating an
interpreter. Threads that create interpreters using \fBTcl_CreateInterp\fR do
not need to call this function, provided that \fBTcl_CreateInterp\fR is the
first call into Tcl from that thread.
.PP
Note that the main thread must have first called either \fBTclZipfs_AppHook\fR
or \fBTcl_FindExecutable\fR to perform application-wide Tcl initialization
before additional threads using Tcl are created. \fBTcl_InitSubsystems\fR does
not suffice for this purpose and should only be used to initialize Tcl in
secondary threads. It need not be called in the main thread invoking one of the
two aforementioned functions.
.PP
The result of \fBTcl_InitSubsystems\fR is the full Tcl version string,
including build information (for example,
\fB9.0.0+abcdef...abcdef.gcc-1002\fR).
.SH KEYWORDS
binary, executable file
