# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

if {![package vsatisfies [package provide Tcl] 9.0]} {return}
package ifneeded memorymoduletest 1.0.0 [list load [file join $dir tcl9memorymoduletest.dll]]
package ifneeded memorymoduletest2 1.0.0 [list load [file join $dir tcl9memorymoduletest2.dll] Memorymoduletest2]
