/*
 * tclDecls.h --
 *
 *	Declarations of functions in the platform independent public Tcl API.
 *
 * Copyright (c) 1998-1999 by Scriptics Corporation.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: @(#) $Id: tclDecls.h,v 1.1 1999/03/03 00:38:39 stanton Exp $
 */

#ifndef _TCLDECLS
#define _TCLDECLS

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the generic/tcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

/* 0 */
EXTERN void		Tcl_AddErrorInfo _ANSI_ARGS_((Tcl_Interp * interp, 
				char * message));
/* 1 */
EXTERN void		Tcl_AddObjErrorInfo _ANSI_ARGS_((Tcl_Interp * interp, 
				char * message, int length));
/* 2 */
EXTERN char *		Tcl_Alloc _ANSI_ARGS_((unsigned int size));
/* 3 */
EXTERN void		Tcl_AllowExceptions _ANSI_ARGS_((Tcl_Interp * interp));
/* 4 */
EXTERN int		Tcl_AppendAllObjTypes _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * objPtr));
/* 5 */
EXTERN void		Tcl_AppendElement _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string));
/* 6 */
EXTERN void		Tcl_AppendResult _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp));
/* 7 */
EXTERN void		Tcl_AppendResultVA _ANSI_ARGS_((Tcl_Interp * interp, 
				va_list argList));
/* 8 */
EXTERN void		Tcl_AppendToObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				char * bytes, int length));
/* 9 */
EXTERN void		Tcl_AppendStringsToObj _ANSI_ARGS_(TCL_VARARGS(Tcl_Obj *,objPtr));
/* 10 */
EXTERN void		Tcl_AppendStringsToObjVA _ANSI_ARGS_((
				Tcl_Obj * objPtr, va_list argList));
/* 11 */
EXTERN Tcl_AsyncHandler	 Tcl_AsyncCreate _ANSI_ARGS_((Tcl_AsyncProc * proc, 
				ClientData clientData));
/* 12 */
EXTERN void		Tcl_AsyncDelete _ANSI_ARGS_((Tcl_AsyncHandler async));
/* 13 */
EXTERN int		Tcl_AsyncInvoke _ANSI_ARGS_((Tcl_Interp * interp, 
				int code));
/* 14 */
EXTERN void		Tcl_AsyncMark _ANSI_ARGS_((Tcl_AsyncHandler async));
/* 15 */
EXTERN int		Tcl_AsyncReady _ANSI_ARGS_((void));
/* 16 */
EXTERN void		Tcl_BackgroundError _ANSI_ARGS_((Tcl_Interp * interp));
/* 17 */
EXTERN char		Tcl_Backslash _ANSI_ARGS_((CONST char * src, 
				int * readPtr));
/* 18 */
EXTERN int		Tcl_BadChannelOption _ANSI_ARGS_((
				Tcl_Interp * interp, char * optionName, 
				char * optionList));
/* 19 */
EXTERN void		Tcl_CallWhenDeleted _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_InterpDeleteProc * proc, 
				ClientData clientData));
/* 20 */
EXTERN void		Tcl_CancelIdleCall _ANSI_ARGS_((
				Tcl_IdleProc * idleProc, 
				ClientData clientData));
/* 21 */
EXTERN int		Tcl_Close _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Channel chan));
/* 22 */
EXTERN int		Tcl_CommandComplete _ANSI_ARGS_((char * cmd));
/* 23 */
EXTERN char *		Tcl_Concat _ANSI_ARGS_((int argc, char ** argv));
/* 24 */
EXTERN Tcl_Obj *	Tcl_ConcatObj _ANSI_ARGS_((int objc, 
				Tcl_Obj *CONST objv[]));
/* 25 */
EXTERN int		Tcl_ConvertCountedElement _ANSI_ARGS_((
				CONST char * src, int length, char * dst, 
				int flags));
/* 26 */
EXTERN int		Tcl_ConvertElement _ANSI_ARGS_((CONST char * src, 
				char * dst, int flags));
/* 27 */
EXTERN int		Tcl_ConvertToType _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, Tcl_ObjType * typePtr));
/* 28 */
EXTERN int		Tcl_CreateAlias _ANSI_ARGS_((Tcl_Interp * slave, 
				char * slaveCmd, Tcl_Interp * target, 
				char * targetCmd, int argc, char ** argv));
/* 29 */
EXTERN int		Tcl_CreateAliasObj _ANSI_ARGS_((Tcl_Interp * slave, 
				char * slaveCmd, Tcl_Interp * target, 
				char * targetCmd, int objc, 
				Tcl_Obj *CONST objv[]));
/* 30 */
EXTERN Tcl_Channel	Tcl_CreateChannel _ANSI_ARGS_((
				Tcl_ChannelType * typePtr, char * chanName, 
				ClientData instanceData, int mask));
/* 31 */
EXTERN void		Tcl_CreateChannelHandler _ANSI_ARGS_((
				Tcl_Channel chan, int mask, 
				Tcl_ChannelProc * proc, 
				ClientData clientData));
/* 32 */
EXTERN void		Tcl_CreateCloseHandler _ANSI_ARGS_((Tcl_Channel chan, 
				Tcl_CloseProc * proc, ClientData clientData));
/* 33 */
EXTERN Tcl_Command	Tcl_CreateCommand _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmdName, Tcl_CmdProc * proc, 
				ClientData clientData, 
				Tcl_CmdDeleteProc * deleteProc));
/* 34 */
EXTERN void		Tcl_CreateEventSource _ANSI_ARGS_((
				Tcl_EventSetupProc * setupProc, 
				Tcl_EventCheckProc * checkProc, 
				ClientData clientData));
/* 35 */
EXTERN void		Tcl_CreateExitHandler _ANSI_ARGS_((
				Tcl_ExitProc * proc, ClientData clientData));
/* 36 */
EXTERN Tcl_Interp *	Tcl_CreateInterp _ANSI_ARGS_((void));
/* 37 */
EXTERN void		Tcl_CreateMathFunc _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, int numArgs, 
				Tcl_ValueType * argTypes, 
				Tcl_MathProc * proc, ClientData clientData));
/* 38 */
EXTERN Tcl_Command	Tcl_CreateObjCommand _ANSI_ARGS_((
				Tcl_Interp * interp, char * cmdName, 
				Tcl_ObjCmdProc * proc, ClientData clientData, 
				Tcl_CmdDeleteProc * deleteProc));
/* 39 */
EXTERN Tcl_Interp *	Tcl_CreateSlave _ANSI_ARGS_((Tcl_Interp * interp, 
				char * slaveName, int isSafe));
/* 40 */
EXTERN Tcl_TimerToken	Tcl_CreateTimerHandler _ANSI_ARGS_((int milliseconds, 
				Tcl_TimerProc * proc, ClientData clientData));
/* 41 */
EXTERN Tcl_Trace	Tcl_CreateTrace _ANSI_ARGS_((Tcl_Interp * interp, 
				int level, Tcl_CmdTraceProc * proc, 
				ClientData clientData));
/* 42 */
EXTERN char *		Tcl_DbCkalloc _ANSI_ARGS_((unsigned int size, 
				char * file, int line));
/* 43 */
EXTERN int		Tcl_DbCkfree _ANSI_ARGS_((char * ptr, char * file, 
				int line));
/* 44 */
EXTERN char *		Tcl_DbCkrealloc _ANSI_ARGS_((char * ptr, 
				unsigned int size, char * file, int line));
/* 45 */
EXTERN void		Tcl_DbDecrRefCount _ANSI_ARGS_((Tcl_Obj * objPtr, 
				char * file, int line));
/* 46 */
EXTERN void		Tcl_DbIncrRefCount _ANSI_ARGS_((Tcl_Obj * objPtr, 
				char * file, int line));
/* 47 */
EXTERN int		Tcl_DbIsShared _ANSI_ARGS_((Tcl_Obj * objPtr, 
				char * file, int line));
/* 48 */
EXTERN Tcl_Obj *	Tcl_DbNewBooleanObj _ANSI_ARGS_((int boolValue, 
				char * file, int line));
/* 49 */
EXTERN Tcl_Obj *	Tcl_DbNewByteArrayObj _ANSI_ARGS_((
				unsigned char * bytes, int length, 
				char * file, int line));
/* 50 */
EXTERN Tcl_Obj *	Tcl_DbNewDoubleObj _ANSI_ARGS_((double doubleValue, 
				char * file, int line));
/* 51 */
EXTERN Tcl_Obj *	Tcl_DbNewListObj _ANSI_ARGS_((int objc, 
				Tcl_Obj *CONST objv[], char * file, int line));
/* 52 */
EXTERN Tcl_Obj *	Tcl_DbNewLongObj _ANSI_ARGS_((long longValue, 
				char * file, int line));
/* 53 */
EXTERN Tcl_Obj *	Tcl_DbNewObj _ANSI_ARGS_((char * file, int line));
/* 54 */
EXTERN Tcl_Obj *	Tcl_DbNewStringObj _ANSI_ARGS_((char * bytes, 
				int length, char * file, int line));
/* 55 */
EXTERN void		Tcl_DeleteAssocData _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name));
/* 56 */
EXTERN int		Tcl_DeleteCommand _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmdName));
/* 57 */
EXTERN int		Tcl_DeleteCommandFromToken _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Command command));
/* 58 */
EXTERN void		Tcl_DeleteChannelHandler _ANSI_ARGS_((
				Tcl_Channel chan, Tcl_ChannelProc * proc, 
				ClientData clientData));
/* 59 */
EXTERN void		Tcl_DeleteCloseHandler _ANSI_ARGS_((Tcl_Channel chan, 
				Tcl_CloseProc * proc, ClientData clientData));
/* 60 */
EXTERN void		Tcl_DeleteEvents _ANSI_ARGS_((
				Tcl_EventDeleteProc * proc, 
				ClientData clientData));
/* 61 */
EXTERN void		Tcl_DeleteEventSource _ANSI_ARGS_((
				Tcl_EventSetupProc * setupProc, 
				Tcl_EventCheckProc * checkProc, 
				ClientData clientData));
/* 62 */
EXTERN void		Tcl_DeleteExitHandler _ANSI_ARGS_((
				Tcl_ExitProc * proc, ClientData clientData));
/* 63 */
EXTERN void		Tcl_DeleteHashEntry _ANSI_ARGS_((
				Tcl_HashEntry * entryPtr));
/* 64 */
EXTERN void		Tcl_DeleteHashTable _ANSI_ARGS_((
				Tcl_HashTable * tablePtr));
/* 65 */
EXTERN void		Tcl_DeleteInterp _ANSI_ARGS_((Tcl_Interp * interp));
/* 66 */
EXTERN void		Tcl_DeleteTimerHandler _ANSI_ARGS_((
				Tcl_TimerToken token));
/* 67 */
EXTERN void		Tcl_DeleteTrace _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Trace trace));
/* 68 */
EXTERN void		Tcl_DetachPids _ANSI_ARGS_((int numPids, 
				Tcl_Pid * pidPtr));
/* 69 */
EXTERN void		Tcl_DontCallWhenDeleted _ANSI_ARGS_((
				Tcl_Interp * interp, 
				Tcl_InterpDeleteProc * proc, 
				ClientData clientData));
/* 70 */
EXTERN int		Tcl_DoOneEvent _ANSI_ARGS_((int flags));
/* 71 */
EXTERN void		Tcl_DoWhenIdle _ANSI_ARGS_((Tcl_IdleProc * proc, 
				ClientData clientData));
/* 72 */
EXTERN char *		Tcl_DStringAppend _ANSI_ARGS_((Tcl_DString * dsPtr, 
				CONST char * string, int length));
/* 73 */
EXTERN char *		Tcl_DStringAppendElement _ANSI_ARGS_((
				Tcl_DString * dsPtr, CONST char * string));
/* 74 */
EXTERN void		Tcl_DStringEndSublist _ANSI_ARGS_((
				Tcl_DString * dsPtr));
/* 75 */
EXTERN void		Tcl_DStringFree _ANSI_ARGS_((Tcl_DString * dsPtr));
/* 76 */
EXTERN void		Tcl_DStringGetResult _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_DString * dsPtr));
/* 77 */
EXTERN void		Tcl_DStringInit _ANSI_ARGS_((Tcl_DString * dsPtr));
/* 78 */
EXTERN void		Tcl_DStringResult _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_DString * dsPtr));
/* 79 */
EXTERN void		Tcl_DStringSetLength _ANSI_ARGS_((
				Tcl_DString * dsPtr, int length));
/* 80 */
EXTERN void		Tcl_DStringStartSublist _ANSI_ARGS_((
				Tcl_DString * dsPtr));
/* 81 */
EXTERN int		Tcl_DumpActiveMemory _ANSI_ARGS_((char * fileName));
/* 82 */
EXTERN Tcl_Obj *	Tcl_DuplicateObj _ANSI_ARGS_((Tcl_Obj * objPtr));
/* 83 */
EXTERN int		Tcl_Eof _ANSI_ARGS_((Tcl_Channel chan));
/* 84 */
EXTERN char *		Tcl_ErrnoId _ANSI_ARGS_((void));
/* 85 */
EXTERN char *		Tcl_ErrnoMsg _ANSI_ARGS_((int err));
/* 86 */
EXTERN int		Tcl_Eval _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string));
/* 87 */
EXTERN int		Tcl_EvalFile _ANSI_ARGS_((Tcl_Interp * interp, 
				char * fileName));
/* 88 */
EXTERN void		Tcl_EventuallyFree _ANSI_ARGS_((
				ClientData clientData, 
				Tcl_FreeProc * freeProc));
/* 89 */
EXTERN int		Tcl_EvalObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr));
/* 90 */
EXTERN void		Tcl_Exit _ANSI_ARGS_((int status));
/* 91 */
EXTERN int		Tcl_ExposeCommand _ANSI_ARGS_((Tcl_Interp * interp, 
				char * hiddenCmdToken, char * cmdName));
/* 92 */
EXTERN int		Tcl_ExprBoolean _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, int * ptr));
/* 93 */
EXTERN int		Tcl_ExprBooleanObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, int * ptr));
/* 94 */
EXTERN int		Tcl_ExprDouble _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, double * ptr));
/* 95 */
EXTERN int		Tcl_ExprDoubleObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, double * ptr));
/* 96 */
EXTERN int		Tcl_ExprLong _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, long * ptr));
/* 97 */
EXTERN int		Tcl_ExprLongObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, long * ptr));
/* 98 */
EXTERN int		Tcl_ExprObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, Tcl_Obj ** resultPtrPtr));
/* 99 */
EXTERN int		Tcl_ExprString _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string));
/* 100 */
EXTERN void		Tcl_Finalize _ANSI_ARGS_((void));
/* 101 */
EXTERN void		Tcl_FindExecutable _ANSI_ARGS_((char * argv0));
/* 102 */
EXTERN Tcl_HashEntry *	Tcl_FirstHashEntry _ANSI_ARGS_((
				Tcl_HashTable * tablePtr, 
				Tcl_HashSearch * searchPtr));
/* 103 */
EXTERN int		Tcl_Flush _ANSI_ARGS_((Tcl_Channel chan));
/* 104 */
EXTERN void		Tcl_Free _ANSI_ARGS_((char * ptr));
/* 105 */
EXTERN void		TclFreeObj _ANSI_ARGS_((Tcl_Obj * objPtr));
/* 106 */
EXTERN void		Tcl_FreeResult _ANSI_ARGS_((Tcl_Interp * interp));
/* 107 */
EXTERN int		Tcl_GetAlias _ANSI_ARGS_((Tcl_Interp * interp, 
				char * slaveCmd, 
				Tcl_Interp ** targetInterpPtr, 
				char ** targetCmdPtr, int * argcPtr, 
				char *** argvPtr));
/* 108 */
EXTERN int		Tcl_GetAliasObj _ANSI_ARGS_((Tcl_Interp * interp, 
				char * slaveCmd, 
				Tcl_Interp ** targetInterpPtr, 
				char ** targetCmdPtr, int * objcPtr, 
				Tcl_Obj *** objv));
/* 109 */
EXTERN ClientData	Tcl_GetAssocData _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, Tcl_InterpDeleteProc ** procPtr));
/* 110 */
EXTERN int		Tcl_GetBoolean _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, int * boolPtr));
/* 111 */
EXTERN int		Tcl_GetBooleanFromObj _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * objPtr, 
				int * boolPtr));
/* 112 */
EXTERN unsigned char *	Tcl_GetByteArrayFromObj _ANSI_ARGS_((
				Tcl_Obj * objPtr, int * lengthPtr));
/* 113 */
EXTERN Tcl_Channel	Tcl_GetChannel _ANSI_ARGS_((Tcl_Interp * interp, 
				char * chanName, int * modePtr));
/* 114 */
EXTERN int		Tcl_GetChannelBufferSize _ANSI_ARGS_((
				Tcl_Channel chan));
/* 115 */
EXTERN int		Tcl_GetChannelHandle _ANSI_ARGS_((Tcl_Channel chan, 
				int direction, ClientData * handlePtr));
/* 116 */
EXTERN ClientData	Tcl_GetChannelInstanceData _ANSI_ARGS_((
				Tcl_Channel chan));
/* 117 */
EXTERN int		Tcl_GetChannelMode _ANSI_ARGS_((Tcl_Channel chan));
/* 118 */
EXTERN char *		Tcl_GetChannelName _ANSI_ARGS_((Tcl_Channel chan));
/* 119 */
EXTERN int		Tcl_GetChannelOption _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Channel chan, 
				char * optionName, Tcl_DString * dsPtr));
/* 120 */
EXTERN Tcl_ChannelType * Tcl_GetChannelType _ANSI_ARGS_((Tcl_Channel chan));
/* 121 */
EXTERN int		Tcl_GetCommandInfo _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmdName, Tcl_CmdInfo * infoPtr));
/* 122 */
EXTERN char *		Tcl_GetCommandName _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Command command));
/* 123 */
EXTERN int		Tcl_GetDouble _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, double * doublePtr));
/* 124 */
EXTERN int		Tcl_GetDoubleFromObj _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * objPtr, 
				double * doublePtr));
/* 125 */
EXTERN int		Tcl_GetErrno _ANSI_ARGS_((void));
/* 126 */
EXTERN char *		Tcl_GetHostName _ANSI_ARGS_((void));
/* 127 */
EXTERN int		Tcl_GetIndexFromObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, char ** tablePtr, 
				char * msg, int flags, int * indexPtr));
/* 128 */
EXTERN int		Tcl_GetInt _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, int * intPtr));
/* 129 */
EXTERN int		Tcl_GetInterpPath _ANSI_ARGS_((
				Tcl_Interp * askInterp, 
				Tcl_Interp * slaveInterp));
/* 130 */
EXTERN int		Tcl_GetIntFromObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, int * intPtr));
/* 131 */
EXTERN int		Tcl_GetLongFromObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr, long * longPtr));
/* 132 */
EXTERN Tcl_Interp *	Tcl_GetMaster _ANSI_ARGS_((Tcl_Interp * interp));
/* 133 */
EXTERN CONST char *	Tcl_GetNameOfExecutable _ANSI_ARGS_((void));
/* 134 */
EXTERN Tcl_Obj *	Tcl_GetObjResult _ANSI_ARGS_((Tcl_Interp * interp));
/* 135 */
EXTERN Tcl_ObjType *	Tcl_GetObjType _ANSI_ARGS_((char * typeName));
/* 136 */
EXTERN Tcl_PathType	Tcl_GetPathType _ANSI_ARGS_((char * path));
/* 137 */
EXTERN int		Tcl_Gets _ANSI_ARGS_((Tcl_Channel chan, 
				Tcl_DString * dsPtr));
/* 138 */
EXTERN int		Tcl_GetsObj _ANSI_ARGS_((Tcl_Channel chan, 
				Tcl_Obj * objPtr));
/* 139 */
EXTERN int		Tcl_GetServiceMode _ANSI_ARGS_((void));
/* 140 */
EXTERN Tcl_Interp *	Tcl_GetSlave _ANSI_ARGS_((Tcl_Interp * interp, 
				char * slaveName));
/* 141 */
EXTERN Tcl_Channel	Tcl_GetStdChannel _ANSI_ARGS_((int type));
/* 142 */
EXTERN char *		Tcl_GetStringFromObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int * lengthPtr));
/* 143 */
EXTERN char *		Tcl_GetStringResult _ANSI_ARGS_((Tcl_Interp * interp));
/* 144 */
EXTERN char *		Tcl_GetVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, int flags));
/* 145 */
EXTERN char *		Tcl_GetVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, int flags));
/* 146 */
EXTERN int		Tcl_GlobalEval _ANSI_ARGS_((Tcl_Interp * interp, 
				char * command));
/* 147 */
EXTERN int		Tcl_GlobalEvalObj _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * objPtr));
/* 148 */
EXTERN char *		Tcl_HashStats _ANSI_ARGS_((Tcl_HashTable * tablePtr));
/* 149 */
EXTERN int		Tcl_HideCommand _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmdName, char * hiddenCmdToken));
/* 150 */
EXTERN int		Tcl_Init _ANSI_ARGS_((Tcl_Interp * interp));
/* 151 */
EXTERN void		Tcl_InitHashTable _ANSI_ARGS_((
				Tcl_HashTable * tablePtr, int keyType));
/* 152 */
EXTERN int		Tcl_InputBlocked _ANSI_ARGS_((Tcl_Channel chan));
/* 153 */
EXTERN int		Tcl_InputBuffered _ANSI_ARGS_((Tcl_Channel chan));
/* 154 */
EXTERN int		Tcl_InterpDeleted _ANSI_ARGS_((Tcl_Interp * interp));
/* 155 */
EXTERN int		Tcl_IsSafe _ANSI_ARGS_((Tcl_Interp * interp));
/* 156 */
EXTERN void		Tcl_InvalidateStringRep _ANSI_ARGS_((
				Tcl_Obj * objPtr));
/* 157 */
EXTERN char *		Tcl_JoinPath _ANSI_ARGS_((int argc, char ** argv, 
				Tcl_DString * resultPtr));
/* 158 */
EXTERN int		Tcl_LinkVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, char * addr, int type));
/* 159 */
EXTERN int		Tcl_ListObjAppendList _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * listPtr, 
				Tcl_Obj * elemListPtr));
/* 160 */
EXTERN int		Tcl_ListObjAppendElement _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * listPtr, 
				Tcl_Obj * objPtr));
/* 161 */
EXTERN int		Tcl_ListObjGetElements _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * listPtr, 
				int * objcPtr, Tcl_Obj *** objvPtr));
/* 162 */
EXTERN int		Tcl_ListObjIndex _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * listPtr, int index, 
				Tcl_Obj ** objPtrPtr));
/* 163 */
EXTERN int		Tcl_ListObjLength _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * listPtr, int * intPtr));
/* 164 */
EXTERN int		Tcl_ListObjReplace _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * listPtr, int first, int count, 
				int objc, Tcl_Obj *CONST objv[]));
/* 165 */
EXTERN Tcl_Channel	Tcl_MakeFileChannel _ANSI_ARGS_((ClientData handle, 
				int mode));
/* 166 */
EXTERN int		Tcl_MakeSafe _ANSI_ARGS_((Tcl_Interp * interp));
/* 167 */
EXTERN Tcl_Channel	Tcl_MakeTcpClientChannel _ANSI_ARGS_((
				ClientData tcpSocket));
/* 168 */
EXTERN char *		Tcl_Merge _ANSI_ARGS_((int argc, char ** argv));
/* 169 */
EXTERN Tcl_Obj *	Tcl_NewBooleanObj _ANSI_ARGS_((int boolValue));
/* 170 */
EXTERN Tcl_Obj *	Tcl_NewByteArrayObj _ANSI_ARGS_((
				unsigned char * bytes, int length));
/* 171 */
EXTERN Tcl_Obj *	Tcl_NewDoubleObj _ANSI_ARGS_((double doubleValue));
/* 172 */
EXTERN Tcl_Obj *	Tcl_NewIntObj _ANSI_ARGS_((int intValue));
/* 173 */
EXTERN Tcl_Obj *	Tcl_NewListObj _ANSI_ARGS_((int objc, 
				Tcl_Obj *CONST objv[]));
/* 174 */
EXTERN Tcl_Obj *	Tcl_NewLongObj _ANSI_ARGS_((long longValue));
/* 175 */
EXTERN Tcl_Obj *	Tcl_NewObj _ANSI_ARGS_((void));
/* 176 */
EXTERN Tcl_Obj *	Tcl_NewStringObj _ANSI_ARGS_((char * bytes, 
				int length));
/* 177 */
EXTERN Tcl_HashEntry *	Tcl_NextHashEntry _ANSI_ARGS_((
				Tcl_HashSearch * searchPtr));
/* 178 */
EXTERN void		Tcl_NotifyChannel _ANSI_ARGS_((Tcl_Channel channel, 
				int mask));
/* 179 */
EXTERN Tcl_Obj *	Tcl_ObjGetVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * part1Ptr, Tcl_Obj * part2Ptr, 
				int flags));
/* 180 */
EXTERN Tcl_Obj *	Tcl_ObjSetVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * part1Ptr, Tcl_Obj * part2Ptr, 
				Tcl_Obj * newValuePtr, int flags));
/* 181 */
EXTERN Tcl_Channel	Tcl_OpenCommandChannel _ANSI_ARGS_((
				Tcl_Interp * interp, int argc, char ** argv, 
				int flags));
/* 182 */
EXTERN Tcl_Channel	Tcl_OpenFileChannel _ANSI_ARGS_((Tcl_Interp * interp, 
				char * fileName, char * modeString, 
				int permissions));
/* 183 */
EXTERN Tcl_Channel	Tcl_OpenTcpClient _ANSI_ARGS_((Tcl_Interp * interp, 
				int port, char * address, char * myaddr, 
				int myport, int async));
/* 184 */
EXTERN Tcl_Channel	Tcl_OpenTcpServer _ANSI_ARGS_((Tcl_Interp * interp, 
				int port, char * host, 
				Tcl_TcpAcceptProc * acceptProc, 
				ClientData callbackData));
/* 185 */
EXTERN void		Tcl_Panic _ANSI_ARGS_(TCL_VARARGS(char *,format));
/* 186 */
EXTERN void		Tcl_PanicVA _ANSI_ARGS_((char * format, 
				va_list argList));
/* 187 */
EXTERN char *		Tcl_ParseVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, char ** termPtr));
/* 188 */
EXTERN char *		Tcl_PkgPresent _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version, int exact));
/* 189 */
EXTERN char *		Tcl_PkgPresentEx _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version, int exact, 
				ClientData * clientDataPtr));
/* 190 */
EXTERN int		Tcl_PkgProvide _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version));
/* 191 */
EXTERN int		Tcl_PkgProvideEx _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version, 
				ClientData clientData));
/* 192 */
EXTERN char *		Tcl_PkgRequire _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version, int exact));
/* 193 */
EXTERN char *		Tcl_PkgRequireEx _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, char * version, int exact, 
				ClientData * clientDataPtr));
/* 194 */
EXTERN char *		Tcl_PosixError _ANSI_ARGS_((Tcl_Interp * interp));
/* 195 */
EXTERN void		Tcl_Preserve _ANSI_ARGS_((ClientData data));
/* 196 */
EXTERN void		Tcl_PrintDouble _ANSI_ARGS_((Tcl_Interp * interp, 
				double value, char * dst));
/* 197 */
EXTERN int		Tcl_PutEnv _ANSI_ARGS_((CONST char * string));
/* 198 */
EXTERN void		Tcl_QueueEvent _ANSI_ARGS_((Tcl_Event * evPtr, 
				Tcl_QueuePosition position));
/* 199 */
EXTERN int		Tcl_Read _ANSI_ARGS_((Tcl_Channel chan, 
				char * bufPtr, int toRead));
/* 200 */
EXTERN char *		Tcl_Realloc _ANSI_ARGS_((char * ptr, 
				unsigned int size));
/* 201 */
EXTERN void		Tcl_ReapDetachedProcs _ANSI_ARGS_((void));
/* 202 */
EXTERN int		Tcl_RecordAndEval _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmd, int flags));
/* 203 */
EXTERN int		Tcl_RecordAndEvalObj _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Obj * cmdPtr, 
				int flags));
/* 204 */
EXTERN Tcl_RegExp	Tcl_RegExpCompile _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string));
/* 205 */
EXTERN int		Tcl_RegExpExec _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_RegExp regexp, char * string, 
				char * start));
/* 206 */
EXTERN int		Tcl_RegExpMatch _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, char * pattern));
/* 207 */
EXTERN void		Tcl_RegExpRange _ANSI_ARGS_((Tcl_RegExp regexp, 
				int index, char ** startPtr, char ** endPtr));
/* 208 */
EXTERN void		Tcl_RegisterChannel _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Channel chan));
/* 209 */
EXTERN void		Tcl_RegisterObjType _ANSI_ARGS_((
				Tcl_ObjType * typePtr));
/* 210 */
EXTERN void		Tcl_Release _ANSI_ARGS_((ClientData clientData));
/* 211 */
EXTERN void		Tcl_ResetResult _ANSI_ARGS_((Tcl_Interp * interp));
/* 212 */
EXTERN int		Tcl_ScanCountedElement _ANSI_ARGS_((
				CONST char * string, int length, 
				int * flagPtr));
/* 213 */
EXTERN int		Tcl_ScanElement _ANSI_ARGS_((CONST char * string, 
				int * flagPtr));
/* 214 */
EXTERN int		Tcl_Seek _ANSI_ARGS_((Tcl_Channel chan, int offset, 
				int mode));
/* 215 */
EXTERN int		Tcl_ServiceAll _ANSI_ARGS_((void));
/* 216 */
EXTERN int		Tcl_ServiceEvent _ANSI_ARGS_((int flags));
/* 217 */
EXTERN void		Tcl_SetAssocData _ANSI_ARGS_((Tcl_Interp * interp, 
				char * name, Tcl_InterpDeleteProc * proc, 
				ClientData clientData));
/* 218 */
EXTERN void		Tcl_SetBooleanObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int boolValue));
/* 219 */
EXTERN unsigned char *	Tcl_SetByteArrayLength _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int length));
/* 220 */
EXTERN void		Tcl_SetByteArrayObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				unsigned char * bytes, int length));
/* 221 */
EXTERN void		Tcl_SetChannelBufferSize _ANSI_ARGS_((
				Tcl_Channel chan, int sz));
/* 222 */
EXTERN int		Tcl_SetChannelOption _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Channel chan, 
				char * optionName, char * newValue));
/* 223 */
EXTERN int		Tcl_SetCommandInfo _ANSI_ARGS_((Tcl_Interp * interp, 
				char * cmdName, Tcl_CmdInfo * infoPtr));
/* 224 */
EXTERN void		Tcl_SetDoubleObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				double doubleValue));
/* 225 */
EXTERN void		Tcl_SetErrno _ANSI_ARGS_((int err));
/* 226 */
EXTERN void		Tcl_SetErrorCode _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp));
/* 227 */
EXTERN void		Tcl_SetErrorCodeVA _ANSI_ARGS_((Tcl_Interp * interp, 
				va_list argList));
/* 228 */
EXTERN void		Tcl_SetIntObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int intValue));
/* 229 */
EXTERN void		Tcl_SetListObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int objc, Tcl_Obj *CONST objv[]));
/* 230 */
EXTERN void		Tcl_SetLongObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				long longValue));
/* 231 */
EXTERN void		Tcl_SetMaxBlockTime _ANSI_ARGS_((Tcl_Time * timePtr));
/* 232 */
EXTERN void		Tcl_SetObjErrorCode _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * errorObjPtr));
/* 233 */
EXTERN void		Tcl_SetObjLength _ANSI_ARGS_((Tcl_Obj * objPtr, 
				int length));
/* 234 */
EXTERN void		Tcl_SetObjResult _ANSI_ARGS_((Tcl_Interp * interp, 
				Tcl_Obj * resultObjPtr));
/* 235 */
EXTERN void		Tcl_SetPanicProc _ANSI_ARGS_((
				Tcl_PanicProc * panicProc));
/* 236 */
EXTERN int		Tcl_SetRecursionLimit _ANSI_ARGS_((
				Tcl_Interp * interp, int depth));
/* 237 */
EXTERN void		Tcl_SetResult _ANSI_ARGS_((Tcl_Interp * interp, 
				char * string, Tcl_FreeProc * freeProc));
/* 238 */
EXTERN int		Tcl_SetServiceMode _ANSI_ARGS_((int mode));
/* 239 */
EXTERN void		Tcl_SetStdChannel _ANSI_ARGS_((Tcl_Channel channel, 
				int type));
/* 240 */
EXTERN void		Tcl_SetStringObj _ANSI_ARGS_((Tcl_Obj * objPtr, 
				char * bytes, int length));
/* 241 */
EXTERN void		Tcl_SetTimer _ANSI_ARGS_((Tcl_Time * timePtr));
/* 242 */
EXTERN char *		Tcl_SetVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, char * newValue, int flags));
/* 243 */
EXTERN char *		Tcl_SetVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, char * newValue, 
				int flags));
/* 244 */
EXTERN char *		Tcl_SignalId _ANSI_ARGS_((int sig));
/* 245 */
EXTERN char *		Tcl_SignalMsg _ANSI_ARGS_((int sig));
/* 246 */
EXTERN void		Tcl_Sleep _ANSI_ARGS_((int ms));
/* 247 */
EXTERN void		Tcl_SourceRCFile _ANSI_ARGS_((Tcl_Interp * interp));
/* 248 */
EXTERN int		Tcl_SplitList _ANSI_ARGS_((Tcl_Interp * interp, 
				char * list, int * argcPtr, char *** argvPtr));
/* 249 */
EXTERN void		Tcl_SplitPath _ANSI_ARGS_((char * path, 
				int * argcPtr, char *** argvPtr));
/* 250 */
EXTERN void		Tcl_StaticPackage _ANSI_ARGS_((Tcl_Interp * interp, 
				char * pkgName, 
				Tcl_PackageInitProc * initProc, 
				Tcl_PackageInitProc * safeInitProc));
/* 251 */
EXTERN int		Tcl_StringMatch _ANSI_ARGS_((char * string, 
				char * pattern));
/* 252 */
EXTERN int		Tcl_Tell _ANSI_ARGS_((Tcl_Channel chan));
/* 253 */
EXTERN int		Tcl_TraceVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, int flags, 
				Tcl_VarTraceProc * proc, 
				ClientData clientData));
/* 254 */
EXTERN int		Tcl_TraceVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, int flags, 
				Tcl_VarTraceProc * proc, 
				ClientData clientData));
/* 255 */
EXTERN char *		Tcl_TranslateFileName _ANSI_ARGS_((
				Tcl_Interp * interp, char * name, 
				Tcl_DString * bufferPtr));
/* 256 */
EXTERN int		Tcl_Ungets _ANSI_ARGS_((Tcl_Channel chan, char * str, 
				int len, int atHead));
/* 257 */
EXTERN void		Tcl_UnlinkVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName));
/* 258 */
EXTERN int		Tcl_UnregisterChannel _ANSI_ARGS_((
				Tcl_Interp * interp, Tcl_Channel chan));
/* 259 */
EXTERN int		Tcl_UnsetVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, int flags));
/* 260 */
EXTERN int		Tcl_UnsetVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, int flags));
/* 261 */
EXTERN void		Tcl_UntraceVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, int flags, 
				Tcl_VarTraceProc * proc, 
				ClientData clientData));
/* 262 */
EXTERN void		Tcl_UntraceVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, int flags, 
				Tcl_VarTraceProc * proc, 
				ClientData clientData));
/* 263 */
EXTERN void		Tcl_UpdateLinkedVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName));
/* 264 */
EXTERN int		Tcl_UpVar _ANSI_ARGS_((Tcl_Interp * interp, 
				char * frameName, char * varName, 
				char * localName, int flags));
/* 265 */
EXTERN int		Tcl_UpVar2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * frameName, char * part1, char * part2, 
				char * localName, int flags));
/* 266 */
EXTERN void		Tcl_ValidateAllMemory _ANSI_ARGS_((char * file, 
				int line));
/* 267 */
EXTERN int		Tcl_VarEval _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp));
/* 268 */
EXTERN int		Tcl_VarEvalVA _ANSI_ARGS_((Tcl_Interp * interp, 
				va_list argList));
/* 269 */
EXTERN ClientData	Tcl_VarTraceInfo _ANSI_ARGS_((Tcl_Interp * interp, 
				char * varName, int flags, 
				Tcl_VarTraceProc * procPtr, 
				ClientData prevClientData));
/* 270 */
EXTERN ClientData	Tcl_VarTraceInfo2 _ANSI_ARGS_((Tcl_Interp * interp, 
				char * part1, char * part2, int flags, 
				Tcl_VarTraceProc * procPtr, 
				ClientData prevClientData));
/* 271 */
EXTERN int		Tcl_WaitForEvent _ANSI_ARGS_((Tcl_Time * timePtr));
/* 272 */
EXTERN Tcl_Pid		Tcl_WaitPid _ANSI_ARGS_((Tcl_Pid pid, int * statPtr, 
				int options));
/* 273 */
EXTERN int		Tcl_Write _ANSI_ARGS_((Tcl_Channel chan, char * s, 
				int slen));
/* 274 */
EXTERN void		Tcl_WrongNumArgs _ANSI_ARGS_((Tcl_Interp * interp, 
				int objc, Tcl_Obj *CONST objv[], 
				char * message));

typedef struct TclStubHooks {
    struct TclPlatStubs *tclPlatStubs;
    struct TclIntStubs *tclIntStubs;
    struct TclIntPlatStubs *tclIntPlatStubs;
} TclStubHooks;

typedef struct TclStubs {
    int magic;
    struct TclStubHooks *hooks;

    void (*tcl_AddErrorInfo) _ANSI_ARGS_((Tcl_Interp * interp, char * message)); /* 0 */
    void (*tcl_AddObjErrorInfo) _ANSI_ARGS_((Tcl_Interp * interp, char * message, int length)); /* 1 */
    char * (*tcl_Alloc) _ANSI_ARGS_((unsigned int size)); /* 2 */
    void (*tcl_AllowExceptions) _ANSI_ARGS_((Tcl_Interp * interp)); /* 3 */
    int (*tcl_AppendAllObjTypes) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr)); /* 4 */
    void (*tcl_AppendElement) _ANSI_ARGS_((Tcl_Interp * interp, char * string)); /* 5 */
    void (*tcl_AppendResult) _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp)); /* 6 */
    void (*tcl_AppendResultVA) _ANSI_ARGS_((Tcl_Interp * interp, va_list argList)); /* 7 */
    void (*tcl_AppendToObj) _ANSI_ARGS_((Tcl_Obj * objPtr, char * bytes, int length)); /* 8 */
    void (*tcl_AppendStringsToObj) _ANSI_ARGS_(TCL_VARARGS(Tcl_Obj *,objPtr)); /* 9 */
    void (*tcl_AppendStringsToObjVA) _ANSI_ARGS_((Tcl_Obj * objPtr, va_list argList)); /* 10 */
    Tcl_AsyncHandler (*tcl_AsyncCreate) _ANSI_ARGS_((Tcl_AsyncProc * proc, ClientData clientData)); /* 11 */
    void (*tcl_AsyncDelete) _ANSI_ARGS_((Tcl_AsyncHandler async)); /* 12 */
    int (*tcl_AsyncInvoke) _ANSI_ARGS_((Tcl_Interp * interp, int code)); /* 13 */
    void (*tcl_AsyncMark) _ANSI_ARGS_((Tcl_AsyncHandler async)); /* 14 */
    int (*tcl_AsyncReady) _ANSI_ARGS_((void)); /* 15 */
    void (*tcl_BackgroundError) _ANSI_ARGS_((Tcl_Interp * interp)); /* 16 */
    char (*tcl_Backslash) _ANSI_ARGS_((CONST char * src, int * readPtr)); /* 17 */
    int (*tcl_BadChannelOption) _ANSI_ARGS_((Tcl_Interp * interp, char * optionName, char * optionList)); /* 18 */
    void (*tcl_CallWhenDeleted) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_InterpDeleteProc * proc, ClientData clientData)); /* 19 */
    void (*tcl_CancelIdleCall) _ANSI_ARGS_((Tcl_IdleProc * idleProc, ClientData clientData)); /* 20 */
    int (*tcl_Close) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Channel chan)); /* 21 */
    int (*tcl_CommandComplete) _ANSI_ARGS_((char * cmd)); /* 22 */
    char * (*tcl_Concat) _ANSI_ARGS_((int argc, char ** argv)); /* 23 */
    Tcl_Obj * (*tcl_ConcatObj) _ANSI_ARGS_((int objc, Tcl_Obj *CONST objv[])); /* 24 */
    int (*tcl_ConvertCountedElement) _ANSI_ARGS_((CONST char * src, int length, char * dst, int flags)); /* 25 */
    int (*tcl_ConvertElement) _ANSI_ARGS_((CONST char * src, char * dst, int flags)); /* 26 */
    int (*tcl_ConvertToType) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, Tcl_ObjType * typePtr)); /* 27 */
    int (*tcl_CreateAlias) _ANSI_ARGS_((Tcl_Interp * slave, char * slaveCmd, Tcl_Interp * target, char * targetCmd, int argc, char ** argv)); /* 28 */
    int (*tcl_CreateAliasObj) _ANSI_ARGS_((Tcl_Interp * slave, char * slaveCmd, Tcl_Interp * target, char * targetCmd, int objc, Tcl_Obj *CONST objv[])); /* 29 */
    Tcl_Channel (*tcl_CreateChannel) _ANSI_ARGS_((Tcl_ChannelType * typePtr, char * chanName, ClientData instanceData, int mask)); /* 30 */
    void (*tcl_CreateChannelHandler) _ANSI_ARGS_((Tcl_Channel chan, int mask, Tcl_ChannelProc * proc, ClientData clientData)); /* 31 */
    void (*tcl_CreateCloseHandler) _ANSI_ARGS_((Tcl_Channel chan, Tcl_CloseProc * proc, ClientData clientData)); /* 32 */
    Tcl_Command (*tcl_CreateCommand) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName, Tcl_CmdProc * proc, ClientData clientData, Tcl_CmdDeleteProc * deleteProc)); /* 33 */
    void (*tcl_CreateEventSource) _ANSI_ARGS_((Tcl_EventSetupProc * setupProc, Tcl_EventCheckProc * checkProc, ClientData clientData)); /* 34 */
    void (*tcl_CreateExitHandler) _ANSI_ARGS_((Tcl_ExitProc * proc, ClientData clientData)); /* 35 */
    Tcl_Interp * (*tcl_CreateInterp) _ANSI_ARGS_((void)); /* 36 */
    void (*tcl_CreateMathFunc) _ANSI_ARGS_((Tcl_Interp * interp, char * name, int numArgs, Tcl_ValueType * argTypes, Tcl_MathProc * proc, ClientData clientData)); /* 37 */
    Tcl_Command (*tcl_CreateObjCommand) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName, Tcl_ObjCmdProc * proc, ClientData clientData, Tcl_CmdDeleteProc * deleteProc)); /* 38 */
    Tcl_Interp * (*tcl_CreateSlave) _ANSI_ARGS_((Tcl_Interp * interp, char * slaveName, int isSafe)); /* 39 */
    Tcl_TimerToken (*tcl_CreateTimerHandler) _ANSI_ARGS_((int milliseconds, Tcl_TimerProc * proc, ClientData clientData)); /* 40 */
    Tcl_Trace (*tcl_CreateTrace) _ANSI_ARGS_((Tcl_Interp * interp, int level, Tcl_CmdTraceProc * proc, ClientData clientData)); /* 41 */
    char * (*tcl_DbCkalloc) _ANSI_ARGS_((unsigned int size, char * file, int line)); /* 42 */
    int (*tcl_DbCkfree) _ANSI_ARGS_((char * ptr, char * file, int line)); /* 43 */
    char * (*tcl_DbCkrealloc) _ANSI_ARGS_((char * ptr, unsigned int size, char * file, int line)); /* 44 */
    void (*tcl_DbDecrRefCount) _ANSI_ARGS_((Tcl_Obj * objPtr, char * file, int line)); /* 45 */
    void (*tcl_DbIncrRefCount) _ANSI_ARGS_((Tcl_Obj * objPtr, char * file, int line)); /* 46 */
    int (*tcl_DbIsShared) _ANSI_ARGS_((Tcl_Obj * objPtr, char * file, int line)); /* 47 */
    Tcl_Obj * (*tcl_DbNewBooleanObj) _ANSI_ARGS_((int boolValue, char * file, int line)); /* 48 */
    Tcl_Obj * (*tcl_DbNewByteArrayObj) _ANSI_ARGS_((unsigned char * bytes, int length, char * file, int line)); /* 49 */
    Tcl_Obj * (*tcl_DbNewDoubleObj) _ANSI_ARGS_((double doubleValue, char * file, int line)); /* 50 */
    Tcl_Obj * (*tcl_DbNewListObj) _ANSI_ARGS_((int objc, Tcl_Obj *CONST objv[], char * file, int line)); /* 51 */
    Tcl_Obj * (*tcl_DbNewLongObj) _ANSI_ARGS_((long longValue, char * file, int line)); /* 52 */
    Tcl_Obj * (*tcl_DbNewObj) _ANSI_ARGS_((char * file, int line)); /* 53 */
    Tcl_Obj * (*tcl_DbNewStringObj) _ANSI_ARGS_((char * bytes, int length, char * file, int line)); /* 54 */
    void (*tcl_DeleteAssocData) _ANSI_ARGS_((Tcl_Interp * interp, char * name)); /* 55 */
    int (*tcl_DeleteCommand) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName)); /* 56 */
    int (*tcl_DeleteCommandFromToken) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Command command)); /* 57 */
    void (*tcl_DeleteChannelHandler) _ANSI_ARGS_((Tcl_Channel chan, Tcl_ChannelProc * proc, ClientData clientData)); /* 58 */
    void (*tcl_DeleteCloseHandler) _ANSI_ARGS_((Tcl_Channel chan, Tcl_CloseProc * proc, ClientData clientData)); /* 59 */
    void (*tcl_DeleteEvents) _ANSI_ARGS_((Tcl_EventDeleteProc * proc, ClientData clientData)); /* 60 */
    void (*tcl_DeleteEventSource) _ANSI_ARGS_((Tcl_EventSetupProc * setupProc, Tcl_EventCheckProc * checkProc, ClientData clientData)); /* 61 */
    void (*tcl_DeleteExitHandler) _ANSI_ARGS_((Tcl_ExitProc * proc, ClientData clientData)); /* 62 */
    void (*tcl_DeleteHashEntry) _ANSI_ARGS_((Tcl_HashEntry * entryPtr)); /* 63 */
    void (*tcl_DeleteHashTable) _ANSI_ARGS_((Tcl_HashTable * tablePtr)); /* 64 */
    void (*tcl_DeleteInterp) _ANSI_ARGS_((Tcl_Interp * interp)); /* 65 */
    void (*tcl_DeleteTimerHandler) _ANSI_ARGS_((Tcl_TimerToken token)); /* 66 */
    void (*tcl_DeleteTrace) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Trace trace)); /* 67 */
    void (*tcl_DetachPids) _ANSI_ARGS_((int numPids, Tcl_Pid * pidPtr)); /* 68 */
    void (*tcl_DontCallWhenDeleted) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_InterpDeleteProc * proc, ClientData clientData)); /* 69 */
    int (*tcl_DoOneEvent) _ANSI_ARGS_((int flags)); /* 70 */
    void (*tcl_DoWhenIdle) _ANSI_ARGS_((Tcl_IdleProc * proc, ClientData clientData)); /* 71 */
    char * (*tcl_DStringAppend) _ANSI_ARGS_((Tcl_DString * dsPtr, CONST char * string, int length)); /* 72 */
    char * (*tcl_DStringAppendElement) _ANSI_ARGS_((Tcl_DString * dsPtr, CONST char * string)); /* 73 */
    void (*tcl_DStringEndSublist) _ANSI_ARGS_((Tcl_DString * dsPtr)); /* 74 */
    void (*tcl_DStringFree) _ANSI_ARGS_((Tcl_DString * dsPtr)); /* 75 */
    void (*tcl_DStringGetResult) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_DString * dsPtr)); /* 76 */
    void (*tcl_DStringInit) _ANSI_ARGS_((Tcl_DString * dsPtr)); /* 77 */
    void (*tcl_DStringResult) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_DString * dsPtr)); /* 78 */
    void (*tcl_DStringSetLength) _ANSI_ARGS_((Tcl_DString * dsPtr, int length)); /* 79 */
    void (*tcl_DStringStartSublist) _ANSI_ARGS_((Tcl_DString * dsPtr)); /* 80 */
    int (*tcl_DumpActiveMemory) _ANSI_ARGS_((char * fileName)); /* 81 */
    Tcl_Obj * (*tcl_DuplicateObj) _ANSI_ARGS_((Tcl_Obj * objPtr)); /* 82 */
    int (*tcl_Eof) _ANSI_ARGS_((Tcl_Channel chan)); /* 83 */
    char * (*tcl_ErrnoId) _ANSI_ARGS_((void)); /* 84 */
    char * (*tcl_ErrnoMsg) _ANSI_ARGS_((int err)); /* 85 */
    int (*tcl_Eval) _ANSI_ARGS_((Tcl_Interp * interp, char * string)); /* 86 */
    int (*tcl_EvalFile) _ANSI_ARGS_((Tcl_Interp * interp, char * fileName)); /* 87 */
    void (*tcl_EventuallyFree) _ANSI_ARGS_((ClientData clientData, Tcl_FreeProc * freeProc)); /* 88 */
    int (*tcl_EvalObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr)); /* 89 */
    void (*tcl_Exit) _ANSI_ARGS_((int status)); /* 90 */
    int (*tcl_ExposeCommand) _ANSI_ARGS_((Tcl_Interp * interp, char * hiddenCmdToken, char * cmdName)); /* 91 */
    int (*tcl_ExprBoolean) _ANSI_ARGS_((Tcl_Interp * interp, char * string, int * ptr)); /* 92 */
    int (*tcl_ExprBooleanObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, int * ptr)); /* 93 */
    int (*tcl_ExprDouble) _ANSI_ARGS_((Tcl_Interp * interp, char * string, double * ptr)); /* 94 */
    int (*tcl_ExprDoubleObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, double * ptr)); /* 95 */
    int (*tcl_ExprLong) _ANSI_ARGS_((Tcl_Interp * interp, char * string, long * ptr)); /* 96 */
    int (*tcl_ExprLongObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, long * ptr)); /* 97 */
    int (*tcl_ExprObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, Tcl_Obj ** resultPtrPtr)); /* 98 */
    int (*tcl_ExprString) _ANSI_ARGS_((Tcl_Interp * interp, char * string)); /* 99 */
    void (*tcl_Finalize) _ANSI_ARGS_((void)); /* 100 */
    void (*tcl_FindExecutable) _ANSI_ARGS_((char * argv0)); /* 101 */
    Tcl_HashEntry * (*tcl_FirstHashEntry) _ANSI_ARGS_((Tcl_HashTable * tablePtr, Tcl_HashSearch * searchPtr)); /* 102 */
    int (*tcl_Flush) _ANSI_ARGS_((Tcl_Channel chan)); /* 103 */
    void (*tcl_Free) _ANSI_ARGS_((char * ptr)); /* 104 */
    void (*tclFreeObj) _ANSI_ARGS_((Tcl_Obj * objPtr)); /* 105 */
    void (*tcl_FreeResult) _ANSI_ARGS_((Tcl_Interp * interp)); /* 106 */
    int (*tcl_GetAlias) _ANSI_ARGS_((Tcl_Interp * interp, char * slaveCmd, Tcl_Interp ** targetInterpPtr, char ** targetCmdPtr, int * argcPtr, char *** argvPtr)); /* 107 */
    int (*tcl_GetAliasObj) _ANSI_ARGS_((Tcl_Interp * interp, char * slaveCmd, Tcl_Interp ** targetInterpPtr, char ** targetCmdPtr, int * objcPtr, Tcl_Obj *** objv)); /* 108 */
    ClientData (*tcl_GetAssocData) _ANSI_ARGS_((Tcl_Interp * interp, char * name, Tcl_InterpDeleteProc ** procPtr)); /* 109 */
    int (*tcl_GetBoolean) _ANSI_ARGS_((Tcl_Interp * interp, char * string, int * boolPtr)); /* 110 */
    int (*tcl_GetBooleanFromObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, int * boolPtr)); /* 111 */
    unsigned char * (*tcl_GetByteArrayFromObj) _ANSI_ARGS_((Tcl_Obj * objPtr, int * lengthPtr)); /* 112 */
    Tcl_Channel (*tcl_GetChannel) _ANSI_ARGS_((Tcl_Interp * interp, char * chanName, int * modePtr)); /* 113 */
    int (*tcl_GetChannelBufferSize) _ANSI_ARGS_((Tcl_Channel chan)); /* 114 */
    int (*tcl_GetChannelHandle) _ANSI_ARGS_((Tcl_Channel chan, int direction, ClientData * handlePtr)); /* 115 */
    ClientData (*tcl_GetChannelInstanceData) _ANSI_ARGS_((Tcl_Channel chan)); /* 116 */
    int (*tcl_GetChannelMode) _ANSI_ARGS_((Tcl_Channel chan)); /* 117 */
    char * (*tcl_GetChannelName) _ANSI_ARGS_((Tcl_Channel chan)); /* 118 */
    int (*tcl_GetChannelOption) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Channel chan, char * optionName, Tcl_DString * dsPtr)); /* 119 */
    Tcl_ChannelType * (*tcl_GetChannelType) _ANSI_ARGS_((Tcl_Channel chan)); /* 120 */
    int (*tcl_GetCommandInfo) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName, Tcl_CmdInfo * infoPtr)); /* 121 */
    char * (*tcl_GetCommandName) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Command command)); /* 122 */
    int (*tcl_GetDouble) _ANSI_ARGS_((Tcl_Interp * interp, char * string, double * doublePtr)); /* 123 */
    int (*tcl_GetDoubleFromObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, double * doublePtr)); /* 124 */
    int (*tcl_GetErrno) _ANSI_ARGS_((void)); /* 125 */
    char * (*tcl_GetHostName) _ANSI_ARGS_((void)); /* 126 */
    int (*tcl_GetIndexFromObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, char ** tablePtr, char * msg, int flags, int * indexPtr)); /* 127 */
    int (*tcl_GetInt) _ANSI_ARGS_((Tcl_Interp * interp, char * string, int * intPtr)); /* 128 */
    int (*tcl_GetInterpPath) _ANSI_ARGS_((Tcl_Interp * askInterp, Tcl_Interp * slaveInterp)); /* 129 */
    int (*tcl_GetIntFromObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, int * intPtr)); /* 130 */
    int (*tcl_GetLongFromObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr, long * longPtr)); /* 131 */
    Tcl_Interp * (*tcl_GetMaster) _ANSI_ARGS_((Tcl_Interp * interp)); /* 132 */
    CONST char * (*tcl_GetNameOfExecutable) _ANSI_ARGS_((void)); /* 133 */
    Tcl_Obj * (*tcl_GetObjResult) _ANSI_ARGS_((Tcl_Interp * interp)); /* 134 */
    Tcl_ObjType * (*tcl_GetObjType) _ANSI_ARGS_((char * typeName)); /* 135 */
    Tcl_PathType (*tcl_GetPathType) _ANSI_ARGS_((char * path)); /* 136 */
    int (*tcl_Gets) _ANSI_ARGS_((Tcl_Channel chan, Tcl_DString * dsPtr)); /* 137 */
    int (*tcl_GetsObj) _ANSI_ARGS_((Tcl_Channel chan, Tcl_Obj * objPtr)); /* 138 */
    int (*tcl_GetServiceMode) _ANSI_ARGS_((void)); /* 139 */
    Tcl_Interp * (*tcl_GetSlave) _ANSI_ARGS_((Tcl_Interp * interp, char * slaveName)); /* 140 */
    Tcl_Channel (*tcl_GetStdChannel) _ANSI_ARGS_((int type)); /* 141 */
    char * (*tcl_GetStringFromObj) _ANSI_ARGS_((Tcl_Obj * objPtr, int * lengthPtr)); /* 142 */
    char * (*tcl_GetStringResult) _ANSI_ARGS_((Tcl_Interp * interp)); /* 143 */
    char * (*tcl_GetVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, int flags)); /* 144 */
    char * (*tcl_GetVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, int flags)); /* 145 */
    int (*tcl_GlobalEval) _ANSI_ARGS_((Tcl_Interp * interp, char * command)); /* 146 */
    int (*tcl_GlobalEvalObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * objPtr)); /* 147 */
    char * (*tcl_HashStats) _ANSI_ARGS_((Tcl_HashTable * tablePtr)); /* 148 */
    int (*tcl_HideCommand) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName, char * hiddenCmdToken)); /* 149 */
    int (*tcl_Init) _ANSI_ARGS_((Tcl_Interp * interp)); /* 150 */
    void (*tcl_InitHashTable) _ANSI_ARGS_((Tcl_HashTable * tablePtr, int keyType)); /* 151 */
    int (*tcl_InputBlocked) _ANSI_ARGS_((Tcl_Channel chan)); /* 152 */
    int (*tcl_InputBuffered) _ANSI_ARGS_((Tcl_Channel chan)); /* 153 */
    int (*tcl_InterpDeleted) _ANSI_ARGS_((Tcl_Interp * interp)); /* 154 */
    int (*tcl_IsSafe) _ANSI_ARGS_((Tcl_Interp * interp)); /* 155 */
    void (*tcl_InvalidateStringRep) _ANSI_ARGS_((Tcl_Obj * objPtr)); /* 156 */
    char * (*tcl_JoinPath) _ANSI_ARGS_((int argc, char ** argv, Tcl_DString * resultPtr)); /* 157 */
    int (*tcl_LinkVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, char * addr, int type)); /* 158 */
    int (*tcl_ListObjAppendList) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, Tcl_Obj * elemListPtr)); /* 159 */
    int (*tcl_ListObjAppendElement) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, Tcl_Obj * objPtr)); /* 160 */
    int (*tcl_ListObjGetElements) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, int * objcPtr, Tcl_Obj *** objvPtr)); /* 161 */
    int (*tcl_ListObjIndex) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, int index, Tcl_Obj ** objPtrPtr)); /* 162 */
    int (*tcl_ListObjLength) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, int * intPtr)); /* 163 */
    int (*tcl_ListObjReplace) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * listPtr, int first, int count, int objc, Tcl_Obj *CONST objv[])); /* 164 */
    Tcl_Channel (*tcl_MakeFileChannel) _ANSI_ARGS_((ClientData handle, int mode)); /* 165 */
    int (*tcl_MakeSafe) _ANSI_ARGS_((Tcl_Interp * interp)); /* 166 */
    Tcl_Channel (*tcl_MakeTcpClientChannel) _ANSI_ARGS_((ClientData tcpSocket)); /* 167 */
    char * (*tcl_Merge) _ANSI_ARGS_((int argc, char ** argv)); /* 168 */
    Tcl_Obj * (*tcl_NewBooleanObj) _ANSI_ARGS_((int boolValue)); /* 169 */
    Tcl_Obj * (*tcl_NewByteArrayObj) _ANSI_ARGS_((unsigned char * bytes, int length)); /* 170 */
    Tcl_Obj * (*tcl_NewDoubleObj) _ANSI_ARGS_((double doubleValue)); /* 171 */
    Tcl_Obj * (*tcl_NewIntObj) _ANSI_ARGS_((int intValue)); /* 172 */
    Tcl_Obj * (*tcl_NewListObj) _ANSI_ARGS_((int objc, Tcl_Obj *CONST objv[])); /* 173 */
    Tcl_Obj * (*tcl_NewLongObj) _ANSI_ARGS_((long longValue)); /* 174 */
    Tcl_Obj * (*tcl_NewObj) _ANSI_ARGS_((void)); /* 175 */
    Tcl_Obj * (*tcl_NewStringObj) _ANSI_ARGS_((char * bytes, int length)); /* 176 */
    Tcl_HashEntry * (*tcl_NextHashEntry) _ANSI_ARGS_((Tcl_HashSearch * searchPtr)); /* 177 */
    void (*tcl_NotifyChannel) _ANSI_ARGS_((Tcl_Channel channel, int mask)); /* 178 */
    Tcl_Obj * (*tcl_ObjGetVar2) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * part1Ptr, Tcl_Obj * part2Ptr, int flags)); /* 179 */
    Tcl_Obj * (*tcl_ObjSetVar2) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * part1Ptr, Tcl_Obj * part2Ptr, Tcl_Obj * newValuePtr, int flags)); /* 180 */
    Tcl_Channel (*tcl_OpenCommandChannel) _ANSI_ARGS_((Tcl_Interp * interp, int argc, char ** argv, int flags)); /* 181 */
    Tcl_Channel (*tcl_OpenFileChannel) _ANSI_ARGS_((Tcl_Interp * interp, char * fileName, char * modeString, int permissions)); /* 182 */
    Tcl_Channel (*tcl_OpenTcpClient) _ANSI_ARGS_((Tcl_Interp * interp, int port, char * address, char * myaddr, int myport, int async)); /* 183 */
    Tcl_Channel (*tcl_OpenTcpServer) _ANSI_ARGS_((Tcl_Interp * interp, int port, char * host, Tcl_TcpAcceptProc * acceptProc, ClientData callbackData)); /* 184 */
    void (*tcl_Panic) _ANSI_ARGS_(TCL_VARARGS(char *,format)); /* 185 */
    void (*tcl_PanicVA) _ANSI_ARGS_((char * format, va_list argList)); /* 186 */
    char * (*tcl_ParseVar) _ANSI_ARGS_((Tcl_Interp * interp, char * string, char ** termPtr)); /* 187 */
    char * (*tcl_PkgPresent) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version, int exact)); /* 188 */
    char * (*tcl_PkgPresentEx) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version, int exact, ClientData * clientDataPtr)); /* 189 */
    int (*tcl_PkgProvide) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version)); /* 190 */
    int (*tcl_PkgProvideEx) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version, ClientData clientData)); /* 191 */
    char * (*tcl_PkgRequire) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version, int exact)); /* 192 */
    char * (*tcl_PkgRequireEx) _ANSI_ARGS_((Tcl_Interp * interp, char * name, char * version, int exact, ClientData * clientDataPtr)); /* 193 */
    char * (*tcl_PosixError) _ANSI_ARGS_((Tcl_Interp * interp)); /* 194 */
    void (*tcl_Preserve) _ANSI_ARGS_((ClientData data)); /* 195 */
    void (*tcl_PrintDouble) _ANSI_ARGS_((Tcl_Interp * interp, double value, char * dst)); /* 196 */
    int (*tcl_PutEnv) _ANSI_ARGS_((CONST char * string)); /* 197 */
    void (*tcl_QueueEvent) _ANSI_ARGS_((Tcl_Event * evPtr, Tcl_QueuePosition position)); /* 198 */
    int (*tcl_Read) _ANSI_ARGS_((Tcl_Channel chan, char * bufPtr, int toRead)); /* 199 */
    char * (*tcl_Realloc) _ANSI_ARGS_((char * ptr, unsigned int size)); /* 200 */
    void (*tcl_ReapDetachedProcs) _ANSI_ARGS_((void)); /* 201 */
    int (*tcl_RecordAndEval) _ANSI_ARGS_((Tcl_Interp * interp, char * cmd, int flags)); /* 202 */
    int (*tcl_RecordAndEvalObj) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * cmdPtr, int flags)); /* 203 */
    Tcl_RegExp (*tcl_RegExpCompile) _ANSI_ARGS_((Tcl_Interp * interp, char * string)); /* 204 */
    int (*tcl_RegExpExec) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_RegExp regexp, char * string, char * start)); /* 205 */
    int (*tcl_RegExpMatch) _ANSI_ARGS_((Tcl_Interp * interp, char * string, char * pattern)); /* 206 */
    void (*tcl_RegExpRange) _ANSI_ARGS_((Tcl_RegExp regexp, int index, char ** startPtr, char ** endPtr)); /* 207 */
    void (*tcl_RegisterChannel) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Channel chan)); /* 208 */
    void (*tcl_RegisterObjType) _ANSI_ARGS_((Tcl_ObjType * typePtr)); /* 209 */
    void (*tcl_Release) _ANSI_ARGS_((ClientData clientData)); /* 210 */
    void (*tcl_ResetResult) _ANSI_ARGS_((Tcl_Interp * interp)); /* 211 */
    int (*tcl_ScanCountedElement) _ANSI_ARGS_((CONST char * string, int length, int * flagPtr)); /* 212 */
    int (*tcl_ScanElement) _ANSI_ARGS_((CONST char * string, int * flagPtr)); /* 213 */
    int (*tcl_Seek) _ANSI_ARGS_((Tcl_Channel chan, int offset, int mode)); /* 214 */
    int (*tcl_ServiceAll) _ANSI_ARGS_((void)); /* 215 */
    int (*tcl_ServiceEvent) _ANSI_ARGS_((int flags)); /* 216 */
    void (*tcl_SetAssocData) _ANSI_ARGS_((Tcl_Interp * interp, char * name, Tcl_InterpDeleteProc * proc, ClientData clientData)); /* 217 */
    void (*tcl_SetBooleanObj) _ANSI_ARGS_((Tcl_Obj * objPtr, int boolValue)); /* 218 */
    unsigned char * (*tcl_SetByteArrayLength) _ANSI_ARGS_((Tcl_Obj * objPtr, int length)); /* 219 */
    void (*tcl_SetByteArrayObj) _ANSI_ARGS_((Tcl_Obj * objPtr, unsigned char * bytes, int length)); /* 220 */
    void (*tcl_SetChannelBufferSize) _ANSI_ARGS_((Tcl_Channel chan, int sz)); /* 221 */
    int (*tcl_SetChannelOption) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Channel chan, char * optionName, char * newValue)); /* 222 */
    int (*tcl_SetCommandInfo) _ANSI_ARGS_((Tcl_Interp * interp, char * cmdName, Tcl_CmdInfo * infoPtr)); /* 223 */
    void (*tcl_SetDoubleObj) _ANSI_ARGS_((Tcl_Obj * objPtr, double doubleValue)); /* 224 */
    void (*tcl_SetErrno) _ANSI_ARGS_((int err)); /* 225 */
    void (*tcl_SetErrorCode) _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp)); /* 226 */
    void (*tcl_SetErrorCodeVA) _ANSI_ARGS_((Tcl_Interp * interp, va_list argList)); /* 227 */
    void (*tcl_SetIntObj) _ANSI_ARGS_((Tcl_Obj * objPtr, int intValue)); /* 228 */
    void (*tcl_SetListObj) _ANSI_ARGS_((Tcl_Obj * objPtr, int objc, Tcl_Obj *CONST objv[])); /* 229 */
    void (*tcl_SetLongObj) _ANSI_ARGS_((Tcl_Obj * objPtr, long longValue)); /* 230 */
    void (*tcl_SetMaxBlockTime) _ANSI_ARGS_((Tcl_Time * timePtr)); /* 231 */
    void (*tcl_SetObjErrorCode) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * errorObjPtr)); /* 232 */
    void (*tcl_SetObjLength) _ANSI_ARGS_((Tcl_Obj * objPtr, int length)); /* 233 */
    void (*tcl_SetObjResult) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Obj * resultObjPtr)); /* 234 */
    void (*tcl_SetPanicProc) _ANSI_ARGS_((Tcl_PanicProc * panicProc)); /* 235 */
    int (*tcl_SetRecursionLimit) _ANSI_ARGS_((Tcl_Interp * interp, int depth)); /* 236 */
    void (*tcl_SetResult) _ANSI_ARGS_((Tcl_Interp * interp, char * string, Tcl_FreeProc * freeProc)); /* 237 */
    int (*tcl_SetServiceMode) _ANSI_ARGS_((int mode)); /* 238 */
    void (*tcl_SetStdChannel) _ANSI_ARGS_((Tcl_Channel channel, int type)); /* 239 */
    void (*tcl_SetStringObj) _ANSI_ARGS_((Tcl_Obj * objPtr, char * bytes, int length)); /* 240 */
    void (*tcl_SetTimer) _ANSI_ARGS_((Tcl_Time * timePtr)); /* 241 */
    char * (*tcl_SetVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, char * newValue, int flags)); /* 242 */
    char * (*tcl_SetVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, char * newValue, int flags)); /* 243 */
    char * (*tcl_SignalId) _ANSI_ARGS_((int sig)); /* 244 */
    char * (*tcl_SignalMsg) _ANSI_ARGS_((int sig)); /* 245 */
    void (*tcl_Sleep) _ANSI_ARGS_((int ms)); /* 246 */
    void (*tcl_SourceRCFile) _ANSI_ARGS_((Tcl_Interp * interp)); /* 247 */
    int (*tcl_SplitList) _ANSI_ARGS_((Tcl_Interp * interp, char * list, int * argcPtr, char *** argvPtr)); /* 248 */
    void (*tcl_SplitPath) _ANSI_ARGS_((char * path, int * argcPtr, char *** argvPtr)); /* 249 */
    void (*tcl_StaticPackage) _ANSI_ARGS_((Tcl_Interp * interp, char * pkgName, Tcl_PackageInitProc * initProc, Tcl_PackageInitProc * safeInitProc)); /* 250 */
    int (*tcl_StringMatch) _ANSI_ARGS_((char * string, char * pattern)); /* 251 */
    int (*tcl_Tell) _ANSI_ARGS_((Tcl_Channel chan)); /* 252 */
    int (*tcl_TraceVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, int flags, Tcl_VarTraceProc * proc, ClientData clientData)); /* 253 */
    int (*tcl_TraceVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, int flags, Tcl_VarTraceProc * proc, ClientData clientData)); /* 254 */
    char * (*tcl_TranslateFileName) _ANSI_ARGS_((Tcl_Interp * interp, char * name, Tcl_DString * bufferPtr)); /* 255 */
    int (*tcl_Ungets) _ANSI_ARGS_((Tcl_Channel chan, char * str, int len, int atHead)); /* 256 */
    void (*tcl_UnlinkVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName)); /* 257 */
    int (*tcl_UnregisterChannel) _ANSI_ARGS_((Tcl_Interp * interp, Tcl_Channel chan)); /* 258 */
    int (*tcl_UnsetVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, int flags)); /* 259 */
    int (*tcl_UnsetVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, int flags)); /* 260 */
    void (*tcl_UntraceVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, int flags, Tcl_VarTraceProc * proc, ClientData clientData)); /* 261 */
    void (*tcl_UntraceVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, int flags, Tcl_VarTraceProc * proc, ClientData clientData)); /* 262 */
    void (*tcl_UpdateLinkedVar) _ANSI_ARGS_((Tcl_Interp * interp, char * varName)); /* 263 */
    int (*tcl_UpVar) _ANSI_ARGS_((Tcl_Interp * interp, char * frameName, char * varName, char * localName, int flags)); /* 264 */
    int (*tcl_UpVar2) _ANSI_ARGS_((Tcl_Interp * interp, char * frameName, char * part1, char * part2, char * localName, int flags)); /* 265 */
    void (*tcl_ValidateAllMemory) _ANSI_ARGS_((char * file, int line)); /* 266 */
    int (*tcl_VarEval) _ANSI_ARGS_(TCL_VARARGS(Tcl_Interp *,interp)); /* 267 */
    int (*tcl_VarEvalVA) _ANSI_ARGS_((Tcl_Interp * interp, va_list argList)); /* 268 */
    ClientData (*tcl_VarTraceInfo) _ANSI_ARGS_((Tcl_Interp * interp, char * varName, int flags, Tcl_VarTraceProc * procPtr, ClientData prevClientData)); /* 269 */
    ClientData (*tcl_VarTraceInfo2) _ANSI_ARGS_((Tcl_Interp * interp, char * part1, char * part2, int flags, Tcl_VarTraceProc * procPtr, ClientData prevClientData)); /* 270 */
    int (*tcl_WaitForEvent) _ANSI_ARGS_((Tcl_Time * timePtr)); /* 271 */
    Tcl_Pid (*tcl_WaitPid) _ANSI_ARGS_((Tcl_Pid pid, int * statPtr, int options)); /* 272 */
    int (*tcl_Write) _ANSI_ARGS_((Tcl_Channel chan, char * s, int slen)); /* 273 */
    void (*tcl_WrongNumArgs) _ANSI_ARGS_((Tcl_Interp * interp, int objc, Tcl_Obj *CONST objv[], char * message)); /* 274 */
} TclStubs;

extern TclStubs *tclStubsPtr;

#if defined(USE_TCL_STUBS) && !defined(USE_TCL_STUB_PROCS)

/*
 * Inline function declarations:
 */

#ifndef Tcl_AddErrorInfo
#define Tcl_AddErrorInfo(interp, message) \
	(tclStubsPtr->tcl_AddErrorInfo)(interp, message) /* 0 */
#endif
#ifndef Tcl_AddObjErrorInfo
#define Tcl_AddObjErrorInfo(interp, message, length) \
	(tclStubsPtr->tcl_AddObjErrorInfo)(interp, message, length) /* 1 */
#endif
#ifndef Tcl_Alloc
#define Tcl_Alloc(size) \
	(tclStubsPtr->tcl_Alloc)(size) /* 2 */
#endif
#ifndef Tcl_AllowExceptions
#define Tcl_AllowExceptions(interp) \
	(tclStubsPtr->tcl_AllowExceptions)(interp) /* 3 */
#endif
#ifndef Tcl_AppendAllObjTypes
#define Tcl_AppendAllObjTypes(interp, objPtr) \
	(tclStubsPtr->tcl_AppendAllObjTypes)(interp, objPtr) /* 4 */
#endif
#ifndef Tcl_AppendElement
#define Tcl_AppendElement(interp, string) \
	(tclStubsPtr->tcl_AppendElement)(interp, string) /* 5 */
#endif
#ifndef Tcl_AppendResult
#define Tcl_AppendResult \
	(tclStubsPtr->tcl_AppendResult) /* 6 */
#endif
#ifndef Tcl_AppendResultVA
#define Tcl_AppendResultVA(interp, argList) \
	(tclStubsPtr->tcl_AppendResultVA)(interp, argList) /* 7 */
#endif
#ifndef Tcl_AppendToObj
#define Tcl_AppendToObj(objPtr, bytes, length) \
	(tclStubsPtr->tcl_AppendToObj)(objPtr, bytes, length) /* 8 */
#endif
#ifndef Tcl_AppendStringsToObj
#define Tcl_AppendStringsToObj \
	(tclStubsPtr->tcl_AppendStringsToObj) /* 9 */
#endif
#ifndef Tcl_AppendStringsToObjVA
#define Tcl_AppendStringsToObjVA(objPtr, argList) \
	(tclStubsPtr->tcl_AppendStringsToObjVA)(objPtr, argList) /* 10 */
#endif
#ifndef Tcl_AsyncCreate
#define Tcl_AsyncCreate(proc, clientData) \
	(tclStubsPtr->tcl_AsyncCreate)(proc, clientData) /* 11 */
#endif
#ifndef Tcl_AsyncDelete
#define Tcl_AsyncDelete(async) \
	(tclStubsPtr->tcl_AsyncDelete)(async) /* 12 */
#endif
#ifndef Tcl_AsyncInvoke
#define Tcl_AsyncInvoke(interp, code) \
	(tclStubsPtr->tcl_AsyncInvoke)(interp, code) /* 13 */
#endif
#ifndef Tcl_AsyncMark
#define Tcl_AsyncMark(async) \
	(tclStubsPtr->tcl_AsyncMark)(async) /* 14 */
#endif
#ifndef Tcl_AsyncReady
#define Tcl_AsyncReady() \
	(tclStubsPtr->tcl_AsyncReady)() /* 15 */
#endif
#ifndef Tcl_BackgroundError
#define Tcl_BackgroundError(interp) \
	(tclStubsPtr->tcl_BackgroundError)(interp) /* 16 */
#endif
#ifndef Tcl_Backslash
#define Tcl_Backslash(src, readPtr) \
	(tclStubsPtr->tcl_Backslash)(src, readPtr) /* 17 */
#endif
#ifndef Tcl_BadChannelOption
#define Tcl_BadChannelOption(interp, optionName, optionList) \
	(tclStubsPtr->tcl_BadChannelOption)(interp, optionName, optionList) /* 18 */
#endif
#ifndef Tcl_CallWhenDeleted
#define Tcl_CallWhenDeleted(interp, proc, clientData) \
	(tclStubsPtr->tcl_CallWhenDeleted)(interp, proc, clientData) /* 19 */
#endif
#ifndef Tcl_CancelIdleCall
#define Tcl_CancelIdleCall(idleProc, clientData) \
	(tclStubsPtr->tcl_CancelIdleCall)(idleProc, clientData) /* 20 */
#endif
#ifndef Tcl_Close
#define Tcl_Close(interp, chan) \
	(tclStubsPtr->tcl_Close)(interp, chan) /* 21 */
#endif
#ifndef Tcl_CommandComplete
#define Tcl_CommandComplete(cmd) \
	(tclStubsPtr->tcl_CommandComplete)(cmd) /* 22 */
#endif
#ifndef Tcl_Concat
#define Tcl_Concat(argc, argv) \
	(tclStubsPtr->tcl_Concat)(argc, argv) /* 23 */
#endif
#ifndef Tcl_ConcatObj
#define Tcl_ConcatObj(objc, objv) \
	(tclStubsPtr->tcl_ConcatObj)(objc, objv) /* 24 */
#endif
#ifndef Tcl_ConvertCountedElement
#define Tcl_ConvertCountedElement(src, length, dst, flags) \
	(tclStubsPtr->tcl_ConvertCountedElement)(src, length, dst, flags) /* 25 */
#endif
#ifndef Tcl_ConvertElement
#define Tcl_ConvertElement(src, dst, flags) \
	(tclStubsPtr->tcl_ConvertElement)(src, dst, flags) /* 26 */
#endif
#ifndef Tcl_ConvertToType
#define Tcl_ConvertToType(interp, objPtr, typePtr) \
	(tclStubsPtr->tcl_ConvertToType)(interp, objPtr, typePtr) /* 27 */
#endif
#ifndef Tcl_CreateAlias
#define Tcl_CreateAlias(slave, slaveCmd, target, targetCmd, argc, argv) \
	(tclStubsPtr->tcl_CreateAlias)(slave, slaveCmd, target, targetCmd, argc, argv) /* 28 */
#endif
#ifndef Tcl_CreateAliasObj
#define Tcl_CreateAliasObj(slave, slaveCmd, target, targetCmd, objc, objv) \
	(tclStubsPtr->tcl_CreateAliasObj)(slave, slaveCmd, target, targetCmd, objc, objv) /* 29 */
#endif
#ifndef Tcl_CreateChannel
#define Tcl_CreateChannel(typePtr, chanName, instanceData, mask) \
	(tclStubsPtr->tcl_CreateChannel)(typePtr, chanName, instanceData, mask) /* 30 */
#endif
#ifndef Tcl_CreateChannelHandler
#define Tcl_CreateChannelHandler(chan, mask, proc, clientData) \
	(tclStubsPtr->tcl_CreateChannelHandler)(chan, mask, proc, clientData) /* 31 */
#endif
#ifndef Tcl_CreateCloseHandler
#define Tcl_CreateCloseHandler(chan, proc, clientData) \
	(tclStubsPtr->tcl_CreateCloseHandler)(chan, proc, clientData) /* 32 */
#endif
#ifndef Tcl_CreateCommand
#define Tcl_CreateCommand(interp, cmdName, proc, clientData, deleteProc) \
	(tclStubsPtr->tcl_CreateCommand)(interp, cmdName, proc, clientData, deleteProc) /* 33 */
#endif
#ifndef Tcl_CreateEventSource
#define Tcl_CreateEventSource(setupProc, checkProc, clientData) \
	(tclStubsPtr->tcl_CreateEventSource)(setupProc, checkProc, clientData) /* 34 */
#endif
#ifndef Tcl_CreateExitHandler
#define Tcl_CreateExitHandler(proc, clientData) \
	(tclStubsPtr->tcl_CreateExitHandler)(proc, clientData) /* 35 */
#endif
#ifndef Tcl_CreateInterp
#define Tcl_CreateInterp() \
	(tclStubsPtr->tcl_CreateInterp)() /* 36 */
#endif
#ifndef Tcl_CreateMathFunc
#define Tcl_CreateMathFunc(interp, name, numArgs, argTypes, proc, clientData) \
	(tclStubsPtr->tcl_CreateMathFunc)(interp, name, numArgs, argTypes, proc, clientData) /* 37 */
#endif
#ifndef Tcl_CreateObjCommand
#define Tcl_CreateObjCommand(interp, cmdName, proc, clientData, deleteProc) \
	(tclStubsPtr->tcl_CreateObjCommand)(interp, cmdName, proc, clientData, deleteProc) /* 38 */
#endif
#ifndef Tcl_CreateSlave
#define Tcl_CreateSlave(interp, slaveName, isSafe) \
	(tclStubsPtr->tcl_CreateSlave)(interp, slaveName, isSafe) /* 39 */
#endif
#ifndef Tcl_CreateTimerHandler
#define Tcl_CreateTimerHandler(milliseconds, proc, clientData) \
	(tclStubsPtr->tcl_CreateTimerHandler)(milliseconds, proc, clientData) /* 40 */
#endif
#ifndef Tcl_CreateTrace
#define Tcl_CreateTrace(interp, level, proc, clientData) \
	(tclStubsPtr->tcl_CreateTrace)(interp, level, proc, clientData) /* 41 */
#endif
#ifndef Tcl_DbCkalloc
#define Tcl_DbCkalloc(size, file, line) \
	(tclStubsPtr->tcl_DbCkalloc)(size, file, line) /* 42 */
#endif
#ifndef Tcl_DbCkfree
#define Tcl_DbCkfree(ptr, file, line) \
	(tclStubsPtr->tcl_DbCkfree)(ptr, file, line) /* 43 */
#endif
#ifndef Tcl_DbCkrealloc
#define Tcl_DbCkrealloc(ptr, size, file, line) \
	(tclStubsPtr->tcl_DbCkrealloc)(ptr, size, file, line) /* 44 */
#endif
#ifndef Tcl_DbDecrRefCount
#define Tcl_DbDecrRefCount(objPtr, file, line) \
	(tclStubsPtr->tcl_DbDecrRefCount)(objPtr, file, line) /* 45 */
#endif
#ifndef Tcl_DbIncrRefCount
#define Tcl_DbIncrRefCount(objPtr, file, line) \
	(tclStubsPtr->tcl_DbIncrRefCount)(objPtr, file, line) /* 46 */
#endif
#ifndef Tcl_DbIsShared
#define Tcl_DbIsShared(objPtr, file, line) \
	(tclStubsPtr->tcl_DbIsShared)(objPtr, file, line) /* 47 */
#endif
#ifndef Tcl_DbNewBooleanObj
#define Tcl_DbNewBooleanObj(boolValue, file, line) \
	(tclStubsPtr->tcl_DbNewBooleanObj)(boolValue, file, line) /* 48 */
#endif
#ifndef Tcl_DbNewByteArrayObj
#define Tcl_DbNewByteArrayObj(bytes, length, file, line) \
	(tclStubsPtr->tcl_DbNewByteArrayObj)(bytes, length, file, line) /* 49 */
#endif
#ifndef Tcl_DbNewDoubleObj
#define Tcl_DbNewDoubleObj(doubleValue, file, line) \
	(tclStubsPtr->tcl_DbNewDoubleObj)(doubleValue, file, line) /* 50 */
#endif
#ifndef Tcl_DbNewListObj
#define Tcl_DbNewListObj(objc, objv, file, line) \
	(tclStubsPtr->tcl_DbNewListObj)(objc, objv, file, line) /* 51 */
#endif
#ifndef Tcl_DbNewLongObj
#define Tcl_DbNewLongObj(longValue, file, line) \
	(tclStubsPtr->tcl_DbNewLongObj)(longValue, file, line) /* 52 */
#endif
#ifndef Tcl_DbNewObj
#define Tcl_DbNewObj(file, line) \
	(tclStubsPtr->tcl_DbNewObj)(file, line) /* 53 */
#endif
#ifndef Tcl_DbNewStringObj
#define Tcl_DbNewStringObj(bytes, length, file, line) \
	(tclStubsPtr->tcl_DbNewStringObj)(bytes, length, file, line) /* 54 */
#endif
#ifndef Tcl_DeleteAssocData
#define Tcl_DeleteAssocData(interp, name) \
	(tclStubsPtr->tcl_DeleteAssocData)(interp, name) /* 55 */
#endif
#ifndef Tcl_DeleteCommand
#define Tcl_DeleteCommand(interp, cmdName) \
	(tclStubsPtr->tcl_DeleteCommand)(interp, cmdName) /* 56 */
#endif
#ifndef Tcl_DeleteCommandFromToken
#define Tcl_DeleteCommandFromToken(interp, command) \
	(tclStubsPtr->tcl_DeleteCommandFromToken)(interp, command) /* 57 */
#endif
#ifndef Tcl_DeleteChannelHandler
#define Tcl_DeleteChannelHandler(chan, proc, clientData) \
	(tclStubsPtr->tcl_DeleteChannelHandler)(chan, proc, clientData) /* 58 */
#endif
#ifndef Tcl_DeleteCloseHandler
#define Tcl_DeleteCloseHandler(chan, proc, clientData) \
	(tclStubsPtr->tcl_DeleteCloseHandler)(chan, proc, clientData) /* 59 */
#endif
#ifndef Tcl_DeleteEvents
#define Tcl_DeleteEvents(proc, clientData) \
	(tclStubsPtr->tcl_DeleteEvents)(proc, clientData) /* 60 */
#endif
#ifndef Tcl_DeleteEventSource
#define Tcl_DeleteEventSource(setupProc, checkProc, clientData) \
	(tclStubsPtr->tcl_DeleteEventSource)(setupProc, checkProc, clientData) /* 61 */
#endif
#ifndef Tcl_DeleteExitHandler
#define Tcl_DeleteExitHandler(proc, clientData) \
	(tclStubsPtr->tcl_DeleteExitHandler)(proc, clientData) /* 62 */
#endif
#ifndef Tcl_DeleteHashEntry
#define Tcl_DeleteHashEntry(entryPtr) \
	(tclStubsPtr->tcl_DeleteHashEntry)(entryPtr) /* 63 */
#endif
#ifndef Tcl_DeleteHashTable
#define Tcl_DeleteHashTable(tablePtr) \
	(tclStubsPtr->tcl_DeleteHashTable)(tablePtr) /* 64 */
#endif
#ifndef Tcl_DeleteInterp
#define Tcl_DeleteInterp(interp) \
	(tclStubsPtr->tcl_DeleteInterp)(interp) /* 65 */
#endif
#ifndef Tcl_DeleteTimerHandler
#define Tcl_DeleteTimerHandler(token) \
	(tclStubsPtr->tcl_DeleteTimerHandler)(token) /* 66 */
#endif
#ifndef Tcl_DeleteTrace
#define Tcl_DeleteTrace(interp, trace) \
	(tclStubsPtr->tcl_DeleteTrace)(interp, trace) /* 67 */
#endif
#ifndef Tcl_DetachPids
#define Tcl_DetachPids(numPids, pidPtr) \
	(tclStubsPtr->tcl_DetachPids)(numPids, pidPtr) /* 68 */
#endif
#ifndef Tcl_DontCallWhenDeleted
#define Tcl_DontCallWhenDeleted(interp, proc, clientData) \
	(tclStubsPtr->tcl_DontCallWhenDeleted)(interp, proc, clientData) /* 69 */
#endif
#ifndef Tcl_DoOneEvent
#define Tcl_DoOneEvent(flags) \
	(tclStubsPtr->tcl_DoOneEvent)(flags) /* 70 */
#endif
#ifndef Tcl_DoWhenIdle
#define Tcl_DoWhenIdle(proc, clientData) \
	(tclStubsPtr->tcl_DoWhenIdle)(proc, clientData) /* 71 */
#endif
#ifndef Tcl_DStringAppend
#define Tcl_DStringAppend(dsPtr, string, length) \
	(tclStubsPtr->tcl_DStringAppend)(dsPtr, string, length) /* 72 */
#endif
#ifndef Tcl_DStringAppendElement
#define Tcl_DStringAppendElement(dsPtr, string) \
	(tclStubsPtr->tcl_DStringAppendElement)(dsPtr, string) /* 73 */
#endif
#ifndef Tcl_DStringEndSublist
#define Tcl_DStringEndSublist(dsPtr) \
	(tclStubsPtr->tcl_DStringEndSublist)(dsPtr) /* 74 */
#endif
#ifndef Tcl_DStringFree
#define Tcl_DStringFree(dsPtr) \
	(tclStubsPtr->tcl_DStringFree)(dsPtr) /* 75 */
#endif
#ifndef Tcl_DStringGetResult
#define Tcl_DStringGetResult(interp, dsPtr) \
	(tclStubsPtr->tcl_DStringGetResult)(interp, dsPtr) /* 76 */
#endif
#ifndef Tcl_DStringInit
#define Tcl_DStringInit(dsPtr) \
	(tclStubsPtr->tcl_DStringInit)(dsPtr) /* 77 */
#endif
#ifndef Tcl_DStringResult
#define Tcl_DStringResult(interp, dsPtr) \
	(tclStubsPtr->tcl_DStringResult)(interp, dsPtr) /* 78 */
#endif
#ifndef Tcl_DStringSetLength
#define Tcl_DStringSetLength(dsPtr, length) \
	(tclStubsPtr->tcl_DStringSetLength)(dsPtr, length) /* 79 */
#endif
#ifndef Tcl_DStringStartSublist
#define Tcl_DStringStartSublist(dsPtr) \
	(tclStubsPtr->tcl_DStringStartSublist)(dsPtr) /* 80 */
#endif
#ifndef Tcl_DumpActiveMemory
#define Tcl_DumpActiveMemory(fileName) \
	(tclStubsPtr->tcl_DumpActiveMemory)(fileName) /* 81 */
#endif
#ifndef Tcl_DuplicateObj
#define Tcl_DuplicateObj(objPtr) \
	(tclStubsPtr->tcl_DuplicateObj)(objPtr) /* 82 */
#endif
#ifndef Tcl_Eof
#define Tcl_Eof(chan) \
	(tclStubsPtr->tcl_Eof)(chan) /* 83 */
#endif
#ifndef Tcl_ErrnoId
#define Tcl_ErrnoId() \
	(tclStubsPtr->tcl_ErrnoId)() /* 84 */
#endif
#ifndef Tcl_ErrnoMsg
#define Tcl_ErrnoMsg(err) \
	(tclStubsPtr->tcl_ErrnoMsg)(err) /* 85 */
#endif
#ifndef Tcl_Eval
#define Tcl_Eval(interp, string) \
	(tclStubsPtr->tcl_Eval)(interp, string) /* 86 */
#endif
#ifndef Tcl_EvalFile
#define Tcl_EvalFile(interp, fileName) \
	(tclStubsPtr->tcl_EvalFile)(interp, fileName) /* 87 */
#endif
#ifndef Tcl_EventuallyFree
#define Tcl_EventuallyFree(clientData, freeProc) \
	(tclStubsPtr->tcl_EventuallyFree)(clientData, freeProc) /* 88 */
#endif
#ifndef Tcl_EvalObj
#define Tcl_EvalObj(interp, objPtr) \
	(tclStubsPtr->tcl_EvalObj)(interp, objPtr) /* 89 */
#endif
#ifndef Tcl_Exit
#define Tcl_Exit(status) \
	(tclStubsPtr->tcl_Exit)(status) /* 90 */
#endif
#ifndef Tcl_ExposeCommand
#define Tcl_ExposeCommand(interp, hiddenCmdToken, cmdName) \
	(tclStubsPtr->tcl_ExposeCommand)(interp, hiddenCmdToken, cmdName) /* 91 */
#endif
#ifndef Tcl_ExprBoolean
#define Tcl_ExprBoolean(interp, string, ptr) \
	(tclStubsPtr->tcl_ExprBoolean)(interp, string, ptr) /* 92 */
#endif
#ifndef Tcl_ExprBooleanObj
#define Tcl_ExprBooleanObj(interp, objPtr, ptr) \
	(tclStubsPtr->tcl_ExprBooleanObj)(interp, objPtr, ptr) /* 93 */
#endif
#ifndef Tcl_ExprDouble
#define Tcl_ExprDouble(interp, string, ptr) \
	(tclStubsPtr->tcl_ExprDouble)(interp, string, ptr) /* 94 */
#endif
#ifndef Tcl_ExprDoubleObj
#define Tcl_ExprDoubleObj(interp, objPtr, ptr) \
	(tclStubsPtr->tcl_ExprDoubleObj)(interp, objPtr, ptr) /* 95 */
#endif
#ifndef Tcl_ExprLong
#define Tcl_ExprLong(interp, string, ptr) \
	(tclStubsPtr->tcl_ExprLong)(interp, string, ptr) /* 96 */
#endif
#ifndef Tcl_ExprLongObj
#define Tcl_ExprLongObj(interp, objPtr, ptr) \
	(tclStubsPtr->tcl_ExprLongObj)(interp, objPtr, ptr) /* 97 */
#endif
#ifndef Tcl_ExprObj
#define Tcl_ExprObj(interp, objPtr, resultPtrPtr) \
	(tclStubsPtr->tcl_ExprObj)(interp, objPtr, resultPtrPtr) /* 98 */
#endif
#ifndef Tcl_ExprString
#define Tcl_ExprString(interp, string) \
	(tclStubsPtr->tcl_ExprString)(interp, string) /* 99 */
#endif
#ifndef Tcl_Finalize
#define Tcl_Finalize() \
	(tclStubsPtr->tcl_Finalize)() /* 100 */
#endif
#ifndef Tcl_FindExecutable
#define Tcl_FindExecutable(argv0) \
	(tclStubsPtr->tcl_FindExecutable)(argv0) /* 101 */
#endif
#ifndef Tcl_FirstHashEntry
#define Tcl_FirstHashEntry(tablePtr, searchPtr) \
	(tclStubsPtr->tcl_FirstHashEntry)(tablePtr, searchPtr) /* 102 */
#endif
#ifndef Tcl_Flush
#define Tcl_Flush(chan) \
	(tclStubsPtr->tcl_Flush)(chan) /* 103 */
#endif
#ifndef Tcl_Free
#define Tcl_Free(ptr) \
	(tclStubsPtr->tcl_Free)(ptr) /* 104 */
#endif
#ifndef TclFreeObj
#define TclFreeObj(objPtr) \
	(tclStubsPtr->tclFreeObj)(objPtr) /* 105 */
#endif
#ifndef Tcl_FreeResult
#define Tcl_FreeResult(interp) \
	(tclStubsPtr->tcl_FreeResult)(interp) /* 106 */
#endif
#ifndef Tcl_GetAlias
#define Tcl_GetAlias(interp, slaveCmd, targetInterpPtr, targetCmdPtr, argcPtr, argvPtr) \
	(tclStubsPtr->tcl_GetAlias)(interp, slaveCmd, targetInterpPtr, targetCmdPtr, argcPtr, argvPtr) /* 107 */
#endif
#ifndef Tcl_GetAliasObj
#define Tcl_GetAliasObj(interp, slaveCmd, targetInterpPtr, targetCmdPtr, objcPtr, objv) \
	(tclStubsPtr->tcl_GetAliasObj)(interp, slaveCmd, targetInterpPtr, targetCmdPtr, objcPtr, objv) /* 108 */
#endif
#ifndef Tcl_GetAssocData
#define Tcl_GetAssocData(interp, name, procPtr) \
	(tclStubsPtr->tcl_GetAssocData)(interp, name, procPtr) /* 109 */
#endif
#ifndef Tcl_GetBoolean
#define Tcl_GetBoolean(interp, string, boolPtr) \
	(tclStubsPtr->tcl_GetBoolean)(interp, string, boolPtr) /* 110 */
#endif
#ifndef Tcl_GetBooleanFromObj
#define Tcl_GetBooleanFromObj(interp, objPtr, boolPtr) \
	(tclStubsPtr->tcl_GetBooleanFromObj)(interp, objPtr, boolPtr) /* 111 */
#endif
#ifndef Tcl_GetByteArrayFromObj
#define Tcl_GetByteArrayFromObj(objPtr, lengthPtr) \
	(tclStubsPtr->tcl_GetByteArrayFromObj)(objPtr, lengthPtr) /* 112 */
#endif
#ifndef Tcl_GetChannel
#define Tcl_GetChannel(interp, chanName, modePtr) \
	(tclStubsPtr->tcl_GetChannel)(interp, chanName, modePtr) /* 113 */
#endif
#ifndef Tcl_GetChannelBufferSize
#define Tcl_GetChannelBufferSize(chan) \
	(tclStubsPtr->tcl_GetChannelBufferSize)(chan) /* 114 */
#endif
#ifndef Tcl_GetChannelHandle
#define Tcl_GetChannelHandle(chan, direction, handlePtr) \
	(tclStubsPtr->tcl_GetChannelHandle)(chan, direction, handlePtr) /* 115 */
#endif
#ifndef Tcl_GetChannelInstanceData
#define Tcl_GetChannelInstanceData(chan) \
	(tclStubsPtr->tcl_GetChannelInstanceData)(chan) /* 116 */
#endif
#ifndef Tcl_GetChannelMode
#define Tcl_GetChannelMode(chan) \
	(tclStubsPtr->tcl_GetChannelMode)(chan) /* 117 */
#endif
#ifndef Tcl_GetChannelName
#define Tcl_GetChannelName(chan) \
	(tclStubsPtr->tcl_GetChannelName)(chan) /* 118 */
#endif
#ifndef Tcl_GetChannelOption
#define Tcl_GetChannelOption(interp, chan, optionName, dsPtr) \
	(tclStubsPtr->tcl_GetChannelOption)(interp, chan, optionName, dsPtr) /* 119 */
#endif
#ifndef Tcl_GetChannelType
#define Tcl_GetChannelType(chan) \
	(tclStubsPtr->tcl_GetChannelType)(chan) /* 120 */
#endif
#ifndef Tcl_GetCommandInfo
#define Tcl_GetCommandInfo(interp, cmdName, infoPtr) \
	(tclStubsPtr->tcl_GetCommandInfo)(interp, cmdName, infoPtr) /* 121 */
#endif
#ifndef Tcl_GetCommandName
#define Tcl_GetCommandName(interp, command) \
	(tclStubsPtr->tcl_GetCommandName)(interp, command) /* 122 */
#endif
#ifndef Tcl_GetDouble
#define Tcl_GetDouble(interp, string, doublePtr) \
	(tclStubsPtr->tcl_GetDouble)(interp, string, doublePtr) /* 123 */
#endif
#ifndef Tcl_GetDoubleFromObj
#define Tcl_GetDoubleFromObj(interp, objPtr, doublePtr) \
	(tclStubsPtr->tcl_GetDoubleFromObj)(interp, objPtr, doublePtr) /* 124 */
#endif
#ifndef Tcl_GetErrno
#define Tcl_GetErrno() \
	(tclStubsPtr->tcl_GetErrno)() /* 125 */
#endif
#ifndef Tcl_GetHostName
#define Tcl_GetHostName() \
	(tclStubsPtr->tcl_GetHostName)() /* 126 */
#endif
#ifndef Tcl_GetIndexFromObj
#define Tcl_GetIndexFromObj(interp, objPtr, tablePtr, msg, flags, indexPtr) \
	(tclStubsPtr->tcl_GetIndexFromObj)(interp, objPtr, tablePtr, msg, flags, indexPtr) /* 127 */
#endif
#ifndef Tcl_GetInt
#define Tcl_GetInt(interp, string, intPtr) \
	(tclStubsPtr->tcl_GetInt)(interp, string, intPtr) /* 128 */
#endif
#ifndef Tcl_GetInterpPath
#define Tcl_GetInterpPath(askInterp, slaveInterp) \
	(tclStubsPtr->tcl_GetInterpPath)(askInterp, slaveInterp) /* 129 */
#endif
#ifndef Tcl_GetIntFromObj
#define Tcl_GetIntFromObj(interp, objPtr, intPtr) \
	(tclStubsPtr->tcl_GetIntFromObj)(interp, objPtr, intPtr) /* 130 */
#endif
#ifndef Tcl_GetLongFromObj
#define Tcl_GetLongFromObj(interp, objPtr, longPtr) \
	(tclStubsPtr->tcl_GetLongFromObj)(interp, objPtr, longPtr) /* 131 */
#endif
#ifndef Tcl_GetMaster
#define Tcl_GetMaster(interp) \
	(tclStubsPtr->tcl_GetMaster)(interp) /* 132 */
#endif
#ifndef Tcl_GetNameOfExecutable
#define Tcl_GetNameOfExecutable() \
	(tclStubsPtr->tcl_GetNameOfExecutable)() /* 133 */
#endif
#ifndef Tcl_GetObjResult
#define Tcl_GetObjResult(interp) \
	(tclStubsPtr->tcl_GetObjResult)(interp) /* 134 */
#endif
#ifndef Tcl_GetObjType
#define Tcl_GetObjType(typeName) \
	(tclStubsPtr->tcl_GetObjType)(typeName) /* 135 */
#endif
#ifndef Tcl_GetPathType
#define Tcl_GetPathType(path) \
	(tclStubsPtr->tcl_GetPathType)(path) /* 136 */
#endif
#ifndef Tcl_Gets
#define Tcl_Gets(chan, dsPtr) \
	(tclStubsPtr->tcl_Gets)(chan, dsPtr) /* 137 */
#endif
#ifndef Tcl_GetsObj
#define Tcl_GetsObj(chan, objPtr) \
	(tclStubsPtr->tcl_GetsObj)(chan, objPtr) /* 138 */
#endif
#ifndef Tcl_GetServiceMode
#define Tcl_GetServiceMode() \
	(tclStubsPtr->tcl_GetServiceMode)() /* 139 */
#endif
#ifndef Tcl_GetSlave
#define Tcl_GetSlave(interp, slaveName) \
	(tclStubsPtr->tcl_GetSlave)(interp, slaveName) /* 140 */
#endif
#ifndef Tcl_GetStdChannel
#define Tcl_GetStdChannel(type) \
	(tclStubsPtr->tcl_GetStdChannel)(type) /* 141 */
#endif
#ifndef Tcl_GetStringFromObj
#define Tcl_GetStringFromObj(objPtr, lengthPtr) \
	(tclStubsPtr->tcl_GetStringFromObj)(objPtr, lengthPtr) /* 142 */
#endif
#ifndef Tcl_GetStringResult
#define Tcl_GetStringResult(interp) \
	(tclStubsPtr->tcl_GetStringResult)(interp) /* 143 */
#endif
#ifndef Tcl_GetVar
#define Tcl_GetVar(interp, varName, flags) \
	(tclStubsPtr->tcl_GetVar)(interp, varName, flags) /* 144 */
#endif
#ifndef Tcl_GetVar2
#define Tcl_GetVar2(interp, part1, part2, flags) \
	(tclStubsPtr->tcl_GetVar2)(interp, part1, part2, flags) /* 145 */
#endif
#ifndef Tcl_GlobalEval
#define Tcl_GlobalEval(interp, command) \
	(tclStubsPtr->tcl_GlobalEval)(interp, command) /* 146 */
#endif
#ifndef Tcl_GlobalEvalObj
#define Tcl_GlobalEvalObj(interp, objPtr) \
	(tclStubsPtr->tcl_GlobalEvalObj)(interp, objPtr) /* 147 */
#endif
#ifndef Tcl_HashStats
#define Tcl_HashStats(tablePtr) \
	(tclStubsPtr->tcl_HashStats)(tablePtr) /* 148 */
#endif
#ifndef Tcl_HideCommand
#define Tcl_HideCommand(interp, cmdName, hiddenCmdToken) \
	(tclStubsPtr->tcl_HideCommand)(interp, cmdName, hiddenCmdToken) /* 149 */
#endif
#ifndef Tcl_Init
#define Tcl_Init(interp) \
	(tclStubsPtr->tcl_Init)(interp) /* 150 */
#endif
#ifndef Tcl_InitHashTable
#define Tcl_InitHashTable(tablePtr, keyType) \
	(tclStubsPtr->tcl_InitHashTable)(tablePtr, keyType) /* 151 */
#endif
#ifndef Tcl_InputBlocked
#define Tcl_InputBlocked(chan) \
	(tclStubsPtr->tcl_InputBlocked)(chan) /* 152 */
#endif
#ifndef Tcl_InputBuffered
#define Tcl_InputBuffered(chan) \
	(tclStubsPtr->tcl_InputBuffered)(chan) /* 153 */
#endif
#ifndef Tcl_InterpDeleted
#define Tcl_InterpDeleted(interp) \
	(tclStubsPtr->tcl_InterpDeleted)(interp) /* 154 */
#endif
#ifndef Tcl_IsSafe
#define Tcl_IsSafe(interp) \
	(tclStubsPtr->tcl_IsSafe)(interp) /* 155 */
#endif
#ifndef Tcl_InvalidateStringRep
#define Tcl_InvalidateStringRep(objPtr) \
	(tclStubsPtr->tcl_InvalidateStringRep)(objPtr) /* 156 */
#endif
#ifndef Tcl_JoinPath
#define Tcl_JoinPath(argc, argv, resultPtr) \
	(tclStubsPtr->tcl_JoinPath)(argc, argv, resultPtr) /* 157 */
#endif
#ifndef Tcl_LinkVar
#define Tcl_LinkVar(interp, varName, addr, type) \
	(tclStubsPtr->tcl_LinkVar)(interp, varName, addr, type) /* 158 */
#endif
#ifndef Tcl_ListObjAppendList
#define Tcl_ListObjAppendList(interp, listPtr, elemListPtr) \
	(tclStubsPtr->tcl_ListObjAppendList)(interp, listPtr, elemListPtr) /* 159 */
#endif
#ifndef Tcl_ListObjAppendElement
#define Tcl_ListObjAppendElement(interp, listPtr, objPtr) \
	(tclStubsPtr->tcl_ListObjAppendElement)(interp, listPtr, objPtr) /* 160 */
#endif
#ifndef Tcl_ListObjGetElements
#define Tcl_ListObjGetElements(interp, listPtr, objcPtr, objvPtr) \
	(tclStubsPtr->tcl_ListObjGetElements)(interp, listPtr, objcPtr, objvPtr) /* 161 */
#endif
#ifndef Tcl_ListObjIndex
#define Tcl_ListObjIndex(interp, listPtr, index, objPtrPtr) \
	(tclStubsPtr->tcl_ListObjIndex)(interp, listPtr, index, objPtrPtr) /* 162 */
#endif
#ifndef Tcl_ListObjLength
#define Tcl_ListObjLength(interp, listPtr, intPtr) \
	(tclStubsPtr->tcl_ListObjLength)(interp, listPtr, intPtr) /* 163 */
#endif
#ifndef Tcl_ListObjReplace
#define Tcl_ListObjReplace(interp, listPtr, first, count, objc, objv) \
	(tclStubsPtr->tcl_ListObjReplace)(interp, listPtr, first, count, objc, objv) /* 164 */
#endif
#ifndef Tcl_MakeFileChannel
#define Tcl_MakeFileChannel(handle, mode) \
	(tclStubsPtr->tcl_MakeFileChannel)(handle, mode) /* 165 */
#endif
#ifndef Tcl_MakeSafe
#define Tcl_MakeSafe(interp) \
	(tclStubsPtr->tcl_MakeSafe)(interp) /* 166 */
#endif
#ifndef Tcl_MakeTcpClientChannel
#define Tcl_MakeTcpClientChannel(tcpSocket) \
	(tclStubsPtr->tcl_MakeTcpClientChannel)(tcpSocket) /* 167 */
#endif
#ifndef Tcl_Merge
#define Tcl_Merge(argc, argv) \
	(tclStubsPtr->tcl_Merge)(argc, argv) /* 168 */
#endif
#ifndef Tcl_NewBooleanObj
#define Tcl_NewBooleanObj(boolValue) \
	(tclStubsPtr->tcl_NewBooleanObj)(boolValue) /* 169 */
#endif
#ifndef Tcl_NewByteArrayObj
#define Tcl_NewByteArrayObj(bytes, length) \
	(tclStubsPtr->tcl_NewByteArrayObj)(bytes, length) /* 170 */
#endif
#ifndef Tcl_NewDoubleObj
#define Tcl_NewDoubleObj(doubleValue) \
	(tclStubsPtr->tcl_NewDoubleObj)(doubleValue) /* 171 */
#endif
#ifndef Tcl_NewIntObj
#define Tcl_NewIntObj(intValue) \
	(tclStubsPtr->tcl_NewIntObj)(intValue) /* 172 */
#endif
#ifndef Tcl_NewListObj
#define Tcl_NewListObj(objc, objv) \
	(tclStubsPtr->tcl_NewListObj)(objc, objv) /* 173 */
#endif
#ifndef Tcl_NewLongObj
#define Tcl_NewLongObj(longValue) \
	(tclStubsPtr->tcl_NewLongObj)(longValue) /* 174 */
#endif
#ifndef Tcl_NewObj
#define Tcl_NewObj() \
	(tclStubsPtr->tcl_NewObj)() /* 175 */
#endif
#ifndef Tcl_NewStringObj
#define Tcl_NewStringObj(bytes, length) \
	(tclStubsPtr->tcl_NewStringObj)(bytes, length) /* 176 */
#endif
#ifndef Tcl_NextHashEntry
#define Tcl_NextHashEntry(searchPtr) \
	(tclStubsPtr->tcl_NextHashEntry)(searchPtr) /* 177 */
#endif
#ifndef Tcl_NotifyChannel
#define Tcl_NotifyChannel(channel, mask) \
	(tclStubsPtr->tcl_NotifyChannel)(channel, mask) /* 178 */
#endif
#ifndef Tcl_ObjGetVar2
#define Tcl_ObjGetVar2(interp, part1Ptr, part2Ptr, flags) \
	(tclStubsPtr->tcl_ObjGetVar2)(interp, part1Ptr, part2Ptr, flags) /* 179 */
#endif
#ifndef Tcl_ObjSetVar2
#define Tcl_ObjSetVar2(interp, part1Ptr, part2Ptr, newValuePtr, flags) \
	(tclStubsPtr->tcl_ObjSetVar2)(interp, part1Ptr, part2Ptr, newValuePtr, flags) /* 180 */
#endif
#ifndef Tcl_OpenCommandChannel
#define Tcl_OpenCommandChannel(interp, argc, argv, flags) \
	(tclStubsPtr->tcl_OpenCommandChannel)(interp, argc, argv, flags) /* 181 */
#endif
#ifndef Tcl_OpenFileChannel
#define Tcl_OpenFileChannel(interp, fileName, modeString, permissions) \
	(tclStubsPtr->tcl_OpenFileChannel)(interp, fileName, modeString, permissions) /* 182 */
#endif
#ifndef Tcl_OpenTcpClient
#define Tcl_OpenTcpClient(interp, port, address, myaddr, myport, async) \
	(tclStubsPtr->tcl_OpenTcpClient)(interp, port, address, myaddr, myport, async) /* 183 */
#endif
#ifndef Tcl_OpenTcpServer
#define Tcl_OpenTcpServer(interp, port, host, acceptProc, callbackData) \
	(tclStubsPtr->tcl_OpenTcpServer)(interp, port, host, acceptProc, callbackData) /* 184 */
#endif
#ifndef Tcl_Panic
#define Tcl_Panic \
	(tclStubsPtr->tcl_Panic) /* 185 */
#endif
#ifndef Tcl_PanicVA
#define Tcl_PanicVA(format, argList) \
	(tclStubsPtr->tcl_PanicVA)(format, argList) /* 186 */
#endif
#ifndef Tcl_ParseVar
#define Tcl_ParseVar(interp, string, termPtr) \
	(tclStubsPtr->tcl_ParseVar)(interp, string, termPtr) /* 187 */
#endif
#ifndef Tcl_PkgPresent
#define Tcl_PkgPresent(interp, name, version, exact) \
	(tclStubsPtr->tcl_PkgPresent)(interp, name, version, exact) /* 188 */
#endif
#ifndef Tcl_PkgPresentEx
#define Tcl_PkgPresentEx(interp, name, version, exact, clientDataPtr) \
	(tclStubsPtr->tcl_PkgPresentEx)(interp, name, version, exact, clientDataPtr) /* 189 */
#endif
#ifndef Tcl_PkgProvide
#define Tcl_PkgProvide(interp, name, version) \
	(tclStubsPtr->tcl_PkgProvide)(interp, name, version) /* 190 */
#endif
#ifndef Tcl_PkgProvideEx
#define Tcl_PkgProvideEx(interp, name, version, clientData) \
	(tclStubsPtr->tcl_PkgProvideEx)(interp, name, version, clientData) /* 191 */
#endif
#ifndef Tcl_PkgRequire
#define Tcl_PkgRequire(interp, name, version, exact) \
	(tclStubsPtr->tcl_PkgRequire)(interp, name, version, exact) /* 192 */
#endif
#ifndef Tcl_PkgRequireEx
#define Tcl_PkgRequireEx(interp, name, version, exact, clientDataPtr) \
	(tclStubsPtr->tcl_PkgRequireEx)(interp, name, version, exact, clientDataPtr) /* 193 */
#endif
#ifndef Tcl_PosixError
#define Tcl_PosixError(interp) \
	(tclStubsPtr->tcl_PosixError)(interp) /* 194 */
#endif
#ifndef Tcl_Preserve
#define Tcl_Preserve(data) \
	(tclStubsPtr->tcl_Preserve)(data) /* 195 */
#endif
#ifndef Tcl_PrintDouble
#define Tcl_PrintDouble(interp, value, dst) \
	(tclStubsPtr->tcl_PrintDouble)(interp, value, dst) /* 196 */
#endif
#ifndef Tcl_PutEnv
#define Tcl_PutEnv(string) \
	(tclStubsPtr->tcl_PutEnv)(string) /* 197 */
#endif
#ifndef Tcl_QueueEvent
#define Tcl_QueueEvent(evPtr, position) \
	(tclStubsPtr->tcl_QueueEvent)(evPtr, position) /* 198 */
#endif
#ifndef Tcl_Read
#define Tcl_Read(chan, bufPtr, toRead) \
	(tclStubsPtr->tcl_Read)(chan, bufPtr, toRead) /* 199 */
#endif
#ifndef Tcl_Realloc
#define Tcl_Realloc(ptr, size) \
	(tclStubsPtr->tcl_Realloc)(ptr, size) /* 200 */
#endif
#ifndef Tcl_ReapDetachedProcs
#define Tcl_ReapDetachedProcs() \
	(tclStubsPtr->tcl_ReapDetachedProcs)() /* 201 */
#endif
#ifndef Tcl_RecordAndEval
#define Tcl_RecordAndEval(interp, cmd, flags) \
	(tclStubsPtr->tcl_RecordAndEval)(interp, cmd, flags) /* 202 */
#endif
#ifndef Tcl_RecordAndEvalObj
#define Tcl_RecordAndEvalObj(interp, cmdPtr, flags) \
	(tclStubsPtr->tcl_RecordAndEvalObj)(interp, cmdPtr, flags) /* 203 */
#endif
#ifndef Tcl_RegExpCompile
#define Tcl_RegExpCompile(interp, string) \
	(tclStubsPtr->tcl_RegExpCompile)(interp, string) /* 204 */
#endif
#ifndef Tcl_RegExpExec
#define Tcl_RegExpExec(interp, regexp, string, start) \
	(tclStubsPtr->tcl_RegExpExec)(interp, regexp, string, start) /* 205 */
#endif
#ifndef Tcl_RegExpMatch
#define Tcl_RegExpMatch(interp, string, pattern) \
	(tclStubsPtr->tcl_RegExpMatch)(interp, string, pattern) /* 206 */
#endif
#ifndef Tcl_RegExpRange
#define Tcl_RegExpRange(regexp, index, startPtr, endPtr) \
	(tclStubsPtr->tcl_RegExpRange)(regexp, index, startPtr, endPtr) /* 207 */
#endif
#ifndef Tcl_RegisterChannel
#define Tcl_RegisterChannel(interp, chan) \
	(tclStubsPtr->tcl_RegisterChannel)(interp, chan) /* 208 */
#endif
#ifndef Tcl_RegisterObjType
#define Tcl_RegisterObjType(typePtr) \
	(tclStubsPtr->tcl_RegisterObjType)(typePtr) /* 209 */
#endif
#ifndef Tcl_Release
#define Tcl_Release(clientData) \
	(tclStubsPtr->tcl_Release)(clientData) /* 210 */
#endif
#ifndef Tcl_ResetResult
#define Tcl_ResetResult(interp) \
	(tclStubsPtr->tcl_ResetResult)(interp) /* 211 */
#endif
#ifndef Tcl_ScanCountedElement
#define Tcl_ScanCountedElement(string, length, flagPtr) \
	(tclStubsPtr->tcl_ScanCountedElement)(string, length, flagPtr) /* 212 */
#endif
#ifndef Tcl_ScanElement
#define Tcl_ScanElement(string, flagPtr) \
	(tclStubsPtr->tcl_ScanElement)(string, flagPtr) /* 213 */
#endif
#ifndef Tcl_Seek
#define Tcl_Seek(chan, offset, mode) \
	(tclStubsPtr->tcl_Seek)(chan, offset, mode) /* 214 */
#endif
#ifndef Tcl_ServiceAll
#define Tcl_ServiceAll() \
	(tclStubsPtr->tcl_ServiceAll)() /* 215 */
#endif
#ifndef Tcl_ServiceEvent
#define Tcl_ServiceEvent(flags) \
	(tclStubsPtr->tcl_ServiceEvent)(flags) /* 216 */
#endif
#ifndef Tcl_SetAssocData
#define Tcl_SetAssocData(interp, name, proc, clientData) \
	(tclStubsPtr->tcl_SetAssocData)(interp, name, proc, clientData) /* 217 */
#endif
#ifndef Tcl_SetBooleanObj
#define Tcl_SetBooleanObj(objPtr, boolValue) \
	(tclStubsPtr->tcl_SetBooleanObj)(objPtr, boolValue) /* 218 */
#endif
#ifndef Tcl_SetByteArrayLength
#define Tcl_SetByteArrayLength(objPtr, length) \
	(tclStubsPtr->tcl_SetByteArrayLength)(objPtr, length) /* 219 */
#endif
#ifndef Tcl_SetByteArrayObj
#define Tcl_SetByteArrayObj(objPtr, bytes, length) \
	(tclStubsPtr->tcl_SetByteArrayObj)(objPtr, bytes, length) /* 220 */
#endif
#ifndef Tcl_SetChannelBufferSize
#define Tcl_SetChannelBufferSize(chan, sz) \
	(tclStubsPtr->tcl_SetChannelBufferSize)(chan, sz) /* 221 */
#endif
#ifndef Tcl_SetChannelOption
#define Tcl_SetChannelOption(interp, chan, optionName, newValue) \
	(tclStubsPtr->tcl_SetChannelOption)(interp, chan, optionName, newValue) /* 222 */
#endif
#ifndef Tcl_SetCommandInfo
#define Tcl_SetCommandInfo(interp, cmdName, infoPtr) \
	(tclStubsPtr->tcl_SetCommandInfo)(interp, cmdName, infoPtr) /* 223 */
#endif
#ifndef Tcl_SetDoubleObj
#define Tcl_SetDoubleObj(objPtr, doubleValue) \
	(tclStubsPtr->tcl_SetDoubleObj)(objPtr, doubleValue) /* 224 */
#endif
#ifndef Tcl_SetErrno
#define Tcl_SetErrno(err) \
	(tclStubsPtr->tcl_SetErrno)(err) /* 225 */
#endif
#ifndef Tcl_SetErrorCode
#define Tcl_SetErrorCode \
	(tclStubsPtr->tcl_SetErrorCode) /* 226 */
#endif
#ifndef Tcl_SetErrorCodeVA
#define Tcl_SetErrorCodeVA(interp, argList) \
	(tclStubsPtr->tcl_SetErrorCodeVA)(interp, argList) /* 227 */
#endif
#ifndef Tcl_SetIntObj
#define Tcl_SetIntObj(objPtr, intValue) \
	(tclStubsPtr->tcl_SetIntObj)(objPtr, intValue) /* 228 */
#endif
#ifndef Tcl_SetListObj
#define Tcl_SetListObj(objPtr, objc, objv) \
	(tclStubsPtr->tcl_SetListObj)(objPtr, objc, objv) /* 229 */
#endif
#ifndef Tcl_SetLongObj
#define Tcl_SetLongObj(objPtr, longValue) \
	(tclStubsPtr->tcl_SetLongObj)(objPtr, longValue) /* 230 */
#endif
#ifndef Tcl_SetMaxBlockTime
#define Tcl_SetMaxBlockTime(timePtr) \
	(tclStubsPtr->tcl_SetMaxBlockTime)(timePtr) /* 231 */
#endif
#ifndef Tcl_SetObjErrorCode
#define Tcl_SetObjErrorCode(interp, errorObjPtr) \
	(tclStubsPtr->tcl_SetObjErrorCode)(interp, errorObjPtr) /* 232 */
#endif
#ifndef Tcl_SetObjLength
#define Tcl_SetObjLength(objPtr, length) \
	(tclStubsPtr->tcl_SetObjLength)(objPtr, length) /* 233 */
#endif
#ifndef Tcl_SetObjResult
#define Tcl_SetObjResult(interp, resultObjPtr) \
	(tclStubsPtr->tcl_SetObjResult)(interp, resultObjPtr) /* 234 */
#endif
#ifndef Tcl_SetPanicProc
#define Tcl_SetPanicProc(panicProc) \
	(tclStubsPtr->tcl_SetPanicProc)(panicProc) /* 235 */
#endif
#ifndef Tcl_SetRecursionLimit
#define Tcl_SetRecursionLimit(interp, depth) \
	(tclStubsPtr->tcl_SetRecursionLimit)(interp, depth) /* 236 */
#endif
#ifndef Tcl_SetResult
#define Tcl_SetResult(interp, string, freeProc) \
	(tclStubsPtr->tcl_SetResult)(interp, string, freeProc) /* 237 */
#endif
#ifndef Tcl_SetServiceMode
#define Tcl_SetServiceMode(mode) \
	(tclStubsPtr->tcl_SetServiceMode)(mode) /* 238 */
#endif
#ifndef Tcl_SetStdChannel
#define Tcl_SetStdChannel(channel, type) \
	(tclStubsPtr->tcl_SetStdChannel)(channel, type) /* 239 */
#endif
#ifndef Tcl_SetStringObj
#define Tcl_SetStringObj(objPtr, bytes, length) \
	(tclStubsPtr->tcl_SetStringObj)(objPtr, bytes, length) /* 240 */
#endif
#ifndef Tcl_SetTimer
#define Tcl_SetTimer(timePtr) \
	(tclStubsPtr->tcl_SetTimer)(timePtr) /* 241 */
#endif
#ifndef Tcl_SetVar
#define Tcl_SetVar(interp, varName, newValue, flags) \
	(tclStubsPtr->tcl_SetVar)(interp, varName, newValue, flags) /* 242 */
#endif
#ifndef Tcl_SetVar2
#define Tcl_SetVar2(interp, part1, part2, newValue, flags) \
	(tclStubsPtr->tcl_SetVar2)(interp, part1, part2, newValue, flags) /* 243 */
#endif
#ifndef Tcl_SignalId
#define Tcl_SignalId(sig) \
	(tclStubsPtr->tcl_SignalId)(sig) /* 244 */
#endif
#ifndef Tcl_SignalMsg
#define Tcl_SignalMsg(sig) \
	(tclStubsPtr->tcl_SignalMsg)(sig) /* 245 */
#endif
#ifndef Tcl_Sleep
#define Tcl_Sleep(ms) \
	(tclStubsPtr->tcl_Sleep)(ms) /* 246 */
#endif
#ifndef Tcl_SourceRCFile
#define Tcl_SourceRCFile(interp) \
	(tclStubsPtr->tcl_SourceRCFile)(interp) /* 247 */
#endif
#ifndef Tcl_SplitList
#define Tcl_SplitList(interp, list, argcPtr, argvPtr) \
	(tclStubsPtr->tcl_SplitList)(interp, list, argcPtr, argvPtr) /* 248 */
#endif
#ifndef Tcl_SplitPath
#define Tcl_SplitPath(path, argcPtr, argvPtr) \
	(tclStubsPtr->tcl_SplitPath)(path, argcPtr, argvPtr) /* 249 */
#endif
#ifndef Tcl_StaticPackage
#define Tcl_StaticPackage(interp, pkgName, initProc, safeInitProc) \
	(tclStubsPtr->tcl_StaticPackage)(interp, pkgName, initProc, safeInitProc) /* 250 */
#endif
#ifndef Tcl_StringMatch
#define Tcl_StringMatch(string, pattern) \
	(tclStubsPtr->tcl_StringMatch)(string, pattern) /* 251 */
#endif
#ifndef Tcl_Tell
#define Tcl_Tell(chan) \
	(tclStubsPtr->tcl_Tell)(chan) /* 252 */
#endif
#ifndef Tcl_TraceVar
#define Tcl_TraceVar(interp, varName, flags, proc, clientData) \
	(tclStubsPtr->tcl_TraceVar)(interp, varName, flags, proc, clientData) /* 253 */
#endif
#ifndef Tcl_TraceVar2
#define Tcl_TraceVar2(interp, part1, part2, flags, proc, clientData) \
	(tclStubsPtr->tcl_TraceVar2)(interp, part1, part2, flags, proc, clientData) /* 254 */
#endif
#ifndef Tcl_TranslateFileName
#define Tcl_TranslateFileName(interp, name, bufferPtr) \
	(tclStubsPtr->tcl_TranslateFileName)(interp, name, bufferPtr) /* 255 */
#endif
#ifndef Tcl_Ungets
#define Tcl_Ungets(chan, str, len, atHead) \
	(tclStubsPtr->tcl_Ungets)(chan, str, len, atHead) /* 256 */
#endif
#ifndef Tcl_UnlinkVar
#define Tcl_UnlinkVar(interp, varName) \
	(tclStubsPtr->tcl_UnlinkVar)(interp, varName) /* 257 */
#endif
#ifndef Tcl_UnregisterChannel
#define Tcl_UnregisterChannel(interp, chan) \
	(tclStubsPtr->tcl_UnregisterChannel)(interp, chan) /* 258 */
#endif
#ifndef Tcl_UnsetVar
#define Tcl_UnsetVar(interp, varName, flags) \
	(tclStubsPtr->tcl_UnsetVar)(interp, varName, flags) /* 259 */
#endif
#ifndef Tcl_UnsetVar2
#define Tcl_UnsetVar2(interp, part1, part2, flags) \
	(tclStubsPtr->tcl_UnsetVar2)(interp, part1, part2, flags) /* 260 */
#endif
#ifndef Tcl_UntraceVar
#define Tcl_UntraceVar(interp, varName, flags, proc, clientData) \
	(tclStubsPtr->tcl_UntraceVar)(interp, varName, flags, proc, clientData) /* 261 */
#endif
#ifndef Tcl_UntraceVar2
#define Tcl_UntraceVar2(interp, part1, part2, flags, proc, clientData) \
	(tclStubsPtr->tcl_UntraceVar2)(interp, part1, part2, flags, proc, clientData) /* 262 */
#endif
#ifndef Tcl_UpdateLinkedVar
#define Tcl_UpdateLinkedVar(interp, varName) \
	(tclStubsPtr->tcl_UpdateLinkedVar)(interp, varName) /* 263 */
#endif
#ifndef Tcl_UpVar
#define Tcl_UpVar(interp, frameName, varName, localName, flags) \
	(tclStubsPtr->tcl_UpVar)(interp, frameName, varName, localName, flags) /* 264 */
#endif
#ifndef Tcl_UpVar2
#define Tcl_UpVar2(interp, frameName, part1, part2, localName, flags) \
	(tclStubsPtr->tcl_UpVar2)(interp, frameName, part1, part2, localName, flags) /* 265 */
#endif
#ifndef Tcl_ValidateAllMemory
#define Tcl_ValidateAllMemory(file, line) \
	(tclStubsPtr->tcl_ValidateAllMemory)(file, line) /* 266 */
#endif
#ifndef Tcl_VarEval
#define Tcl_VarEval \
	(tclStubsPtr->tcl_VarEval) /* 267 */
#endif
#ifndef Tcl_VarEvalVA
#define Tcl_VarEvalVA(interp, argList) \
	(tclStubsPtr->tcl_VarEvalVA)(interp, argList) /* 268 */
#endif
#ifndef Tcl_VarTraceInfo
#define Tcl_VarTraceInfo(interp, varName, flags, procPtr, prevClientData) \
	(tclStubsPtr->tcl_VarTraceInfo)(interp, varName, flags, procPtr, prevClientData) /* 269 */
#endif
#ifndef Tcl_VarTraceInfo2
#define Tcl_VarTraceInfo2(interp, part1, part2, flags, procPtr, prevClientData) \
	(tclStubsPtr->tcl_VarTraceInfo2)(interp, part1, part2, flags, procPtr, prevClientData) /* 270 */
#endif
#ifndef Tcl_WaitForEvent
#define Tcl_WaitForEvent(timePtr) \
	(tclStubsPtr->tcl_WaitForEvent)(timePtr) /* 271 */
#endif
#ifndef Tcl_WaitPid
#define Tcl_WaitPid(pid, statPtr, options) \
	(tclStubsPtr->tcl_WaitPid)(pid, statPtr, options) /* 272 */
#endif
#ifndef Tcl_Write
#define Tcl_Write(chan, s, slen) \
	(tclStubsPtr->tcl_Write)(chan, s, slen) /* 273 */
#endif
#ifndef Tcl_WrongNumArgs
#define Tcl_WrongNumArgs(interp, objc, objv, message) \
	(tclStubsPtr->tcl_WrongNumArgs)(interp, objc, objv, message) /* 274 */
#endif

#endif /* defined(USE_TCL_STUBS) && !defined(USE_TCL_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* _TCLDECLS */

