name: msys2

on:
  push:

jobs:
  msys2:
    runs-on: windows-2025

    defaults:
      run:
        shell: msys2 {0}
        working-directory: unix

    steps:
      - name: Init MSYS
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git base-devel msys2-devel zlib-devel
          update: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          ./configure -C --prefix=/usr --enable-64bit || { cat config.log; cat config.cache; exit 1; }
          make
      - name: Run Tests (ignoring test io-53.4.1 which hangs)
        run: make test
        env:
          ERROR_ON_FAILURES: 1
          TESTFLAGS: -skip io-53.4.1
